"¼Ó
DDeviceIDLE"IDLE1Ûù~jëê@AÛù~jëê@Q
6 ŸYï?Y
6 ŸYï?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_23/dense_70/MatMul(1ÇK7‰A *@9ÇK7‰A *@AÇK7‰A *@IÇK7‰A *@QˆÓ½Ãë/?YüEò>[ï?ŠUnknown
sDeviceMatMul"sequential_23/dense_69/MatMul(1ÇK7‰A *@9ÇK7‰A *@AÇK7‰A *@IÇK7‰A *@QˆÓ½Ãë/?YÙ®]]ï?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_23/dense_69/MatMul(1ú~j¼t“(@9ú~j¼t“(@Aú~j¼t“(@Iú~j¼t“(@Qùß*âÂ,?Y‡¤ÜII_ï?ŠUnknown
sDeviceMatMul"sequential_23/dense_70/MatMul(1ú~j¼t“(@9ú~j¼t“(@Aú~j¼t“(@Iú~j¼t“(@Qùß*âÂ,?Y5Ç
6aï?ŠUnknown
mDeviceMul"Nadam/Nadam/update_3/mul_2(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@QNM§¤2<*?Yª5ù¶bï?ŠUnknown
ƒDeviceMatMul"-gradient_tape/sequential_23/dense_70/MatMul_1(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@QNM§¤2<*?Y\_¼Zdï?ŠUnknown
‹DeviceDynamicStitch".gradient_tape/mean_squared_error/DynamicStitch(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Q§™®ñ± ?Y¯EzÛeeï?ŠUnknown
“	DeviceBiasAddGrad"8gradient_tape/sequential_23/dense_71/BiasAdd/BiasAddGrad(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Q§™®ñ± ?Y?/•úpfï?ŠUnknown
ƒ
DeviceMatMul"-gradient_tape/sequential_23/dense_71/MatMul_1(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Q§™®ñ± ?YÏ°|gï?ŠUnknown
sDeviceMatMul"sequential_23/dense_71/MatMul(1NbX9´@9NbX9´@ANbX9´@INbX9´@Q$æëÄ?YèHAbhï?ŠUnknown
ŸDeviceSquaredDifference">sequential_23/batch_normalization_46/moments/SquaredDifference(1®Gáz”@9®Gáz”@A®Gáz”@I®Gáz”@QÂ¡I*ôŸ?Y5›°@Giï?ŠUnknown
gDevice
LogicalAnd"
LogicalAnd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YŒ¬Ç6,jï?ŠUnknown
^DeviceCast"
Nadam/Cast(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?YªåÚëjï?ŠUnknown
qDeviceRealDiv"Nadam/Nadam/update/truediv(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?YÈîĞ©kï?ŠUnknown
‰DeviceTile"5gradient_tape/mean_squared_error/weighted_loss/Tile_1(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?YæWhlï?ŠUnknown
‘DeviceSub">gradient_tape/sequential_23/batch_normalization_46/moments/sub(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Y‘k'mï?ŠUnknown
›DeviceSum"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/add_1/Sum_1(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Y"Ê'8æmï?ŠUnknown
™DeviceMul"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_1/Mul(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Y@;¥nï?ŠUnknown
“DeviceBiasAddGrad"8gradient_tape/sequential_23/dense_70/BiasAdd/BiasAddGrad(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Y^<NÒcoï?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_23/dense_71/MatMul(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Y|uaŸ"pï?ŠUnknown
…DeviceMean"1sequential_23/batch_normalization_46/moments/mean(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Yš®tlápï?ŠUnknown
ŸDeviceSquaredDifference">sequential_23/batch_normalization_47/moments/SquaredDifference(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q¥º#g¢Ù?Y¸ç‡9 qï?ŠUnknown
‰DeviceAddV2"4sequential_23/batch_normalization_46/batchnorm/add_1(1'1¬Z@9'1¬Z@A'1¬Z@I'1¬Z@QzKcy³?YSÕ]rï?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_2(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QW;4³?Yï£ì‚örï?ŠUnknown
uDeviceRealDiv"Nadam/Nadam/update_8/truediv_3(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QW;4³?YÊE†0sï?ŠUnknown
¡DeviceBroadcastTo"Fgradient_tape/sequential_23/batch_normalization_46/moments/BroadcastTo(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QW;4³?Y¥çŞ'tï?ŠUnknown
™DeviceRealDiv"Bgradient_tape/sequential_23/batch_normalization_46/moments/truediv(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QW;4³?Y€‰¹‹Àtï?ŠUnknown
ƒDeviceEluGrad",gradient_tape/sequential_23/dense_70/EluGrad(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QW;4³?Y[+S9Yuï?ŠUnknown
kDeviceSqrt"Nadam/Nadam/update/Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y@Œbİñuï?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y%íqŠvï?ŠUnknown
s DeviceRealDiv"Nadam/Nadam/update/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y
N%#wï?ŠUnknown
u!DeviceRealDiv"Nadam/Nadam/update_1/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yï®É»wï?ŠUnknown
m"DeviceMul"Nadam/Nadam/update_2/mul_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YÔ mTxï?ŠUnknown
s#DeviceRealDiv"Nadam/Nadam/update_2/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y¹p¯íxï?ŠUnknown
u$DeviceRealDiv"Nadam/Nadam/update_3/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YÑ¾µ…yï?ŠUnknown
m%DeviceSqrt"Nadam/Nadam/update_4/Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yƒ2ÎYzï?ŠUnknown
o&DeviceAddV2"Nadam/Nadam/update_4/add_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yh“İı¶zï?ŠUnknown
k'DeviceMul"Nadam/Nadam/update_4/mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YMôì¡O{ï?ŠUnknown
m(DeviceMul"Nadam/Nadam/update_4/mul_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y2UüEè{ï?ŠUnknown
m)DeviceMul"Nadam/Nadam/update_4/mul_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y¶ê€|ï?ŠUnknown
m*DeviceMul"Nadam/Nadam/update_4/mul_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yü}ï?ŠUnknown
m+DeviceMul"Nadam/Nadam/update_4/mul_4(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yáw*2²}ï?ŠUnknown
k,DeviceSub"Nadam/Nadam/update_4/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YÆØ9ÖJ~ï?ŠUnknown
s-DeviceRealDiv"Nadam/Nadam/update_4/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y«9Izã~ï?ŠUnknown
u.DeviceRealDiv"Nadam/Nadam/update_4/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YšX|ï?ŠUnknown
u/DeviceRealDiv"Nadam/Nadam/update_4/truediv_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YuûgÂ€ï?ŠUnknown
u0DeviceRealDiv"Nadam/Nadam/update_4/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YZ\wf­€ï?ŠUnknown
s1DeviceRealDiv"Nadam/Nadam/update_5/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y?½†
Fï?ŠUnknown
u2DeviceRealDiv"Nadam/Nadam/update_5/truediv_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y$–®Şï?ŠUnknown
u3DeviceRealDiv"Nadam/Nadam/update_5/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y	¥Rw‚ï?ŠUnknown
u4DeviceRealDiv"Nadam/Nadam/update_6/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yîß´öƒï?ŠUnknown
u5DeviceRealDiv"Nadam/Nadam/update_7/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YÓ@Äš¨ƒï?ŠUnknown
s6DeviceRealDiv"Nadam/Nadam/update_8/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y¸¡Ó>A„ï?ŠUnknown
^7DevicePow"Nadam/Pow_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YãâÙ„ï?ŠUnknown
j8DeviceAddN"Nadam/gradients/AddN_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y‚cò†r…ï?ŠUnknown
j9DeviceAddN"Nadam/gradients/AddN_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YgÄ+†ï?ŠUnknown
X:DeviceSqrt"Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YL%Ï£†ï?ŠUnknown
X;DeviceSum"Sum_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y1† s<‡ï?ŠUnknown
<DeviceRealDiv"(gradient_tape/mean_squared_error/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yç/Õ‡ï?ŠUnknown
—=DeviceDivNoNan"?gradient_tape/mean_squared_error/weighted_loss/value/div_no_nan(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YûG?»mˆï?ŠUnknown
›>DeviceSum"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/add_1/Sum_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yà¨N_‰ï?ŠUnknown
™?DeviceMul"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_1/Mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YÅ	^Ÿ‰ï?ŠUnknown
›@DeviceSum"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_1/Sum_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yªjm§7Šï?ŠUnknown
£ADeviceBroadcastTo"Hgradient_tape/sequential_23/batch_normalization_46/moments/BroadcastTo_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YË|KĞŠï?ŠUnknown
›BDeviceRealDiv"Dgradient_tape/sequential_23/batch_normalization_46/moments/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yt,Œïh‹ï?ŠUnknown
¡CDeviceBroadcastTo"Fgradient_tape/sequential_23/batch_normalization_47/moments/BroadcastTo(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YY›“Œï?ŠUnknown
£DDeviceBroadcastTo"Hgradient_tape/sequential_23/batch_normalization_47/moments/BroadcastTo_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y>îª7šŒï?ŠUnknown
‘EDeviceSub">gradient_tape/sequential_23/batch_normalization_47/moments/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y#OºÛ2ï?ŠUnknown
™FDeviceRealDiv"Bgradient_tape/sequential_23/batch_normalization_47/moments/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y°ÉËï?ŠUnknown
“GDeviceBiasAddGrad"8gradient_tape/sequential_23/dense_69/BiasAdd/BiasAddGrad(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YíÙ#dï?ŠUnknown
‡HDeviceMul"4sequential_23/batch_normalization_46/batchnorm/mul_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YÒqèÇüï?ŠUnknown
…IDeviceSub"2sequential_23/batch_normalization_46/batchnorm/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y·Ò÷k•ï?ŠUnknown
‰JDeviceMean"5sequential_23/batch_normalization_46/moments/variance(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yœ3.ï?ŠUnknown
‡KDeviceAddV2"2sequential_23/batch_normalization_47/batchnorm/add(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y”´Æï?ŠUnknown
‰LDeviceAddV2"4sequential_23/batch_normalization_47/batchnorm/add_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Yfõ%X_‘ï?ŠUnknown
‡MDeviceMul"4sequential_23/batch_normalization_47/batchnorm/mul_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YKV5ü÷‘ï?ŠUnknown
…NDeviceMean"1sequential_23/batch_normalization_47/moments/mean(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?Y0·D ’ï?ŠUnknown
‰ODeviceMean"5sequential_23/batch_normalization_47/moments/variance(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YTD)“ï?ŠUnknown
uPDeviceBiasAdd"sequential_23/dense_69/BiasAdd(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YúxcèÁ“ï?ŠUnknown
mQDeviceElu"sequential_23/dense_69/Elu(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QQ•ì?YßÙrŒZ”ï?ŠUnknown
~RDeviceDivNoNan"&mean_squared_error/weighted_loss/value(1¨ÆK7‰A@9¨ÆK7‰A@A¨ÆK7‰A@I¨ÆK7‰A@Q&\DèXî?Y:ÿñ”ï?ŠUnknown
uSDeviceRealDiv"Nadam/Nadam/update_9/truediv_3(1¢E¶óıÔ@9¢E¶óıÔ@A¢E¶óıÔ@I¢E¶óıÔ@QNRÛéë?YoÃ«e•ï?ŠUnknown
xTDeviceAssignAddVariableOp"AssignAddVariableOp_3(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y#0Ø•ï?ŠUnknown
oUDeviceSquare"Nadam/Nadam/update/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y³V¹´J–ï?ŠUnknown
mVDeviceAddV2"Nadam/Nadam/update/add_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YU O9½–ï?ŠUnknown
iWDeviceMul"Nadam/Nadam/update/mul(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y÷éä½/—ï?ŠUnknown
qXDeviceSquare"Nadam/Nadam/update_1/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y™³zB¢—ï?ŠUnknown
oYDeviceAddV2"Nadam/Nadam/update_1/add_1(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y;}Ç˜ï?ŠUnknown
kZDeviceSub"Nadam/Nadam/update_2/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YİF¦K‡˜ï?ŠUnknown
q[DeviceSquare"Nadam/Nadam/update_3/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y<Ğù˜ï?ŠUnknown
m\DeviceMul"Nadam/Nadam/update_3/mul_3(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y!ÚÑTl™ï?ŠUnknown
q]DeviceSquare"Nadam/Nadam/update_4/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YÃ£gÙŞ™ï?ŠUnknown
o^DeviceAddV2"Nadam/Nadam/update_4/add_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Yemı]Qšï?ŠUnknown
q_DeviceSquare"Nadam/Nadam/update_5/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y7“âÃšï?ŠUnknown
o`DeviceAddV2"Nadam/Nadam/update_5/add_1(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y© )g6›ï?ŠUnknown
maDeviceMul"Nadam/Nadam/update_5/mul_6(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YKÊ¾ë¨›ï?ŠUnknown
mbDeviceMul"Nadam/Nadam/update_6/mul_3(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Yí“Tpœï?ŠUnknown
mcDeviceMul"Nadam/Nadam/update_6/mul_6(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y]êôœï?ŠUnknown
mdDeviceMul"Nadam/Nadam/update_7/mul_1(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y1'€y ï?ŠUnknown
qeDeviceSquare"Nadam/Nadam/update_8/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YÓğşrï?ŠUnknown
mfDeviceMul"Nadam/Nadam/update_9/mul_4(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Yuº«‚åï?ŠUnknown
ugDeviceRealDiv"Nadam/Nadam/update_9/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y„AXï?ŠUnknown
bhDeviceDivNoNan"
div_no_nan(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y¹M×‹Êï?ŠUnknown
—iDeviceNeg"Dgradient_tape/sequential_23/batch_normalization_46/batchnorm/sub/Neg(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Y[m=Ÿï?ŠUnknown
“jDeviceCast"?gradient_tape/sequential_23/batch_normalization_47/moments/Cast(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?Yıà•¯Ÿï?ŠUnknown
‹kDeviceMul"8sequential_23/batch_normalization_47/AssignMovingAvg/mul(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YŸª˜" ï?ŠUnknown
ulDeviceBiasAdd"sequential_23/dense_70/BiasAdd(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q‹chr%¡?YAt.” ï?ŠUnknown
vmDeviceAssignAddVariableOp"AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yìü9¡ï?ŠUnknown
xnDeviceAssignAddVariableOp"AssignAddVariableOp_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y—…E”y¡ï?ŠUnknown
xoDeviceAssignAddVariableOp"AssignAddVariableOp_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YBQì¡ï?ŠUnknown
xpDeviceAssignAddVariableOp"AssignAddVariableOp_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yí–\Š^¢ï?ŠUnknown
XqDeviceCast"Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y˜hÑ¢ï?ŠUnknown
ZrDeviceCast"Cast_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YC¨s€C£ï?ŠUnknown
VsDeviceMul"Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yî0ûµ£ï?ŠUnknown
`tDeviceCast"Nadam/Cast_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y™¹Šv(¤ï?ŠUnknown
`uDeviceCast"Nadam/Cast_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YDB–ñš¤ï?ŠUnknown
‚vDeviceAssignAddVariableOp"Nadam/Nadam/AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YïÊ¡l¥ï?ŠUnknown
kwDeviceAddV2"Nadam/Nadam/update/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YšS­ç¥ï?ŠUnknown
mxDeviceAddV2"Nadam/Nadam/update/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YEÜ¸bò¥ï?ŠUnknown
myDeviceAddV2"Nadam/Nadam/update/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YğdÄİd¦ï?ŠUnknown
kzDeviceMul"Nadam/Nadam/update/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y›íÏX×¦ï?ŠUnknown
k{DeviceMul"Nadam/Nadam/update/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YFvÛÓI§ï?ŠUnknown
k|DeviceMul"Nadam/Nadam/update/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YñşæN¼§ï?ŠUnknown
k}DeviceMul"Nadam/Nadam/update/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yœ‡òÉ.¨ï?ŠUnknown
k~DeviceMul"Nadam/Nadam/update/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YGşD¡¨ï?ŠUnknown
iDeviceSub"Nadam/Nadam/update/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yò˜	À©ï?ŠUnknown
n€DeviceAddV2"Nadam/Nadam/update_1/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y!;†©ï?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_1/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YHª ¶ø©ï?ŠUnknown
p‚DeviceAddV2"Nadam/Nadam/update_1/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yó2,1kªï?ŠUnknown
lƒDeviceMul"Nadam/Nadam/update_1/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y»7¬İªï?ŠUnknown
n„DeviceMul"Nadam/Nadam/update_1/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YIDC'P«ï?ŠUnknown
n…DeviceMul"Nadam/Nadam/update_1/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YôÌN¢Â«ï?ŠUnknown
n†DeviceMul"Nadam/Nadam/update_1/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YŸUZ5¬ï?ŠUnknown
n‡DeviceMul"Nadam/Nadam/update_1/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YJŞe˜§¬ï?ŠUnknown
nˆDeviceMul"Nadam/Nadam/update_1/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yõfq­ï?ŠUnknown
n‰DeviceMul"Nadam/Nadam/update_1/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y ï|Œ­ï?ŠUnknown
tŠDeviceRealDiv"Nadam/Nadam/update_1/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YKxˆ	ÿ­ï?ŠUnknown
v‹DeviceRealDiv"Nadam/Nadam/update_1/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yö ”„q®ï?ŠUnknown
vŒDeviceRealDiv"Nadam/Nadam/update_1/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¡‰Ÿÿã®ï?ŠUnknown
nDeviceSqrt"Nadam/Nadam/update_2/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YL«zV¯ï?ŠUnknown
rDeviceSquare"Nadam/Nadam/update_2/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y÷š¶õÈ¯ï?ŠUnknown
nDeviceAddV2"Nadam/Nadam/update_2/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¢#Âp;°ï?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_2/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YM¬Íë­°ï?ŠUnknown
p‘DeviceAddV2"Nadam/Nadam/update_2/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yø4Ùf ±ï?ŠUnknown
p’DeviceAddV2"Nadam/Nadam/update_2/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y£½äá’±ï?ŠUnknown
l“DeviceMul"Nadam/Nadam/update_2/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YNFğ\²ï?ŠUnknown
n”DeviceMul"Nadam/Nadam/update_2/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YùÎû×w²ï?ŠUnknown
n•DeviceMul"Nadam/Nadam/update_2/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¤WSê²ï?ŠUnknown
v–DeviceRealDiv"Nadam/Nadam/update_2/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YOàÎ\³ï?ŠUnknown
v—DeviceRealDiv"Nadam/Nadam/update_2/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YúhIÏ³ï?ŠUnknown
v˜DeviceRealDiv"Nadam/Nadam/update_2/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¥ñ)ÄA´ï?ŠUnknown
n™DeviceSqrt"Nadam/Nadam/update_3/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YPz5?´´ï?ŠUnknown
nšDeviceAddV2"Nadam/Nadam/update_3/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YûAº&µï?ŠUnknown
p›DeviceAddV2"Nadam/Nadam/update_3/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¦‹L5™µï?ŠUnknown
pœDeviceAddV2"Nadam/Nadam/update_3/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YQX°¶ï?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_3/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yüœc+~¶ï?ŠUnknown
nDeviceMul"Nadam/Nadam/update_3/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y§%o¦ğ¶ï?ŠUnknown
nŸDeviceMul"Nadam/Nadam/update_3/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YR®z!c·ï?ŠUnknown
l DeviceSub"Nadam/Nadam/update_3/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yı6†œÕ·ï?ŠUnknown
t¡DeviceRealDiv"Nadam/Nadam/update_3/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¨¿‘H¸ï?ŠUnknown
v¢DeviceRealDiv"Nadam/Nadam/update_3/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YSH’º¸ï?ŠUnknown
v£DeviceRealDiv"Nadam/Nadam/update_3/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YşĞ¨-¹ï?ŠUnknown
n¤DeviceAddV2"Nadam/Nadam/update_4/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y©Y´ˆŸ¹ï?ŠUnknown
p¥DeviceAddV2"Nadam/Nadam/update_4/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YTâ¿ºï?ŠUnknown
n¦DeviceMul"Nadam/Nadam/update_4/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÿjË~„ºï?ŠUnknown
n§DeviceMul"Nadam/Nadam/update_4/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YªóÖùöºï?ŠUnknown
n¨DeviceSqrt"Nadam/Nadam/update_5/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YU|âti»ï?ŠUnknown
n©DeviceAddV2"Nadam/Nadam/update_5/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y îïÛ»ï?ŠUnknown
pªDeviceAddV2"Nadam/Nadam/update_5/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y«ùjN¼ï?ŠUnknown
n«DeviceMul"Nadam/Nadam/update_5/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YVæÀ¼ï?ŠUnknown
n¬DeviceMul"Nadam/Nadam/update_5/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YŸa3½ï?ŠUnknown
n­DeviceMul"Nadam/Nadam/update_5/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¬'Ü¥½ï?ŠUnknown
l®DeviceSub"Nadam/Nadam/update_5/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YW°'W¾ï?ŠUnknown
v¯DeviceRealDiv"Nadam/Nadam/update_5/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y93ÒŠ¾ï?ŠUnknown
n°DeviceSqrt"Nadam/Nadam/update_6/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y­Á>Mı¾ï?ŠUnknown
r±DeviceSquare"Nadam/Nadam/update_6/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YXJJÈo¿ï?ŠUnknown
n²DeviceAddV2"Nadam/Nadam/update_6/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÓUCâ¿ï?ŠUnknown
p³DeviceAddV2"Nadam/Nadam/update_6/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y®[a¾TÀï?ŠUnknown
p´DeviceAddV2"Nadam/Nadam/update_6/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YYäl9ÇÀï?ŠUnknown
pµDeviceAddV2"Nadam/Nadam/update_6/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ymx´9Áï?ŠUnknown
n¶DeviceMul"Nadam/Nadam/update_6/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¯õƒ/¬Áï?ŠUnknown
n·DeviceMul"Nadam/Nadam/update_6/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YZ~ªÂï?ŠUnknown
t¸DeviceRealDiv"Nadam/Nadam/update_6/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y›%‘Âï?ŠUnknown
v¹DeviceRealDiv"Nadam/Nadam/update_6/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y°¦ Ãï?ŠUnknown
vºDeviceRealDiv"Nadam/Nadam/update_6/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y[²vÃï?ŠUnknown
n»DeviceSqrt"Nadam/Nadam/update_7/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¡½–èÃï?ŠUnknown
r¼DeviceSquare"Nadam/Nadam/update_7/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y±)É[Äï?ŠUnknown
n½DeviceAddV2"Nadam/Nadam/update_7/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y\²ÔŒÍÄï?ŠUnknown
p¾DeviceAddV2"Nadam/Nadam/update_7/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y;à@Åï?ŠUnknown
p¿DeviceAddV2"Nadam/Nadam/update_7/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y²Ãë‚²Åï?ŠUnknown
pÀDeviceAddV2"Nadam/Nadam/update_7/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y]L÷ı$Æï?ŠUnknown
lÁDeviceMul"Nadam/Nadam/update_7/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÕy—Æï?ŠUnknown
nÂDeviceMul"Nadam/Nadam/update_7/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y³]ô	Çï?ŠUnknown
nÃDeviceMul"Nadam/Nadam/update_7/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y^æo|Çï?ŠUnknown
nÄDeviceMul"Nadam/Nadam/update_7/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y	o%êîÇï?ŠUnknown
nÅDeviceMul"Nadam/Nadam/update_7/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y´÷0eaÈï?ŠUnknown
lÆDeviceSub"Nadam/Nadam/update_7/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y_€<àÓÈï?ŠUnknown
tÇDeviceRealDiv"Nadam/Nadam/update_7/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y
	H[FÉï?ŠUnknown
vÈDeviceRealDiv"Nadam/Nadam/update_7/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yµ‘SÖ¸Éï?ŠUnknown
vÉDeviceRealDiv"Nadam/Nadam/update_7/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y`_Q+Êï?ŠUnknown
nÊDeviceSqrt"Nadam/Nadam/update_8/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y£jÌÊï?ŠUnknown
nËDeviceAddV2"Nadam/Nadam/update_8/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¶+vGËï?ŠUnknown
pÌDeviceAddV2"Nadam/Nadam/update_8/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ya´Â‚Ëï?ŠUnknown
pÍDeviceAddV2"Nadam/Nadam/update_8/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y==õËï?ŠUnknown
pÎDeviceAddV2"Nadam/Nadam/update_8/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y·Å˜¸gÌï?ŠUnknown
lÏDeviceMul"Nadam/Nadam/update_8/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YbN¤3ÚÌï?ŠUnknown
nĞDeviceMul"Nadam/Nadam/update_8/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y×¯®LÍï?ŠUnknown
nÑDeviceMul"Nadam/Nadam/update_8/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¸_»)¿Íï?ŠUnknown
nÒDeviceMul"Nadam/Nadam/update_8/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YcèÆ¤1Îï?ŠUnknown
nÓDeviceMul"Nadam/Nadam/update_8/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YqÒ¤Îï?ŠUnknown
nÔDeviceMul"Nadam/Nadam/update_8/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¹ùİšÏï?ŠUnknown
lÕDeviceSub"Nadam/Nadam/update_8/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yd‚é‰Ïï?ŠUnknown
vÖDeviceRealDiv"Nadam/Nadam/update_8/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YõûÏï?ŠUnknown
v×DeviceRealDiv"Nadam/Nadam/update_8/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yº“ nĞï?ŠUnknown
nØDeviceSqrt"Nadam/Nadam/update_9/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ye‡àĞï?ŠUnknown
rÙDeviceSquare"Nadam/Nadam/update_9/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¥SÑï?ŠUnknown
nÚDeviceAddV2"Nadam/Nadam/update_9/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y»-#}ÅÑï?ŠUnknown
pÛDeviceAddV2"Nadam/Nadam/update_9/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yf¶.ø7Òï?ŠUnknown
lÜDeviceMul"Nadam/Nadam/update_9/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y?:sªÒï?ŠUnknown
nİDeviceMul"Nadam/Nadam/update_9/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¼ÇEîÓï?ŠUnknown
nŞDeviceMul"Nadam/Nadam/update_9/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YgPQiÓï?ŠUnknown
nßDeviceMul"Nadam/Nadam/update_9/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÙ\äÔï?ŠUnknown
nàDeviceMul"Nadam/Nadam/update_9/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y½ah_tÔï?ŠUnknown
láDeviceSub"Nadam/Nadam/update_9/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YhêsÚæÔï?ŠUnknown
vâDeviceRealDiv"Nadam/Nadam/update_9/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YsUYÕï?ŠUnknown
]ãDevicePow"	Nadam/Pow(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¾ûŠĞËÕï?ŠUnknown
_äDevicePow"Nadam/Pow_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yi„–K>Öï?ŠUnknown
_åDeviceAddV2"	Nadam/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¢Æ°Öï?ŠUnknown
aæDeviceAddV2"Nadam/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y¿•­A#×ï?ŠUnknown
içDeviceAddN"Nadam/gradients/AddN(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yj¹¼•×ï?ŠUnknown
kèDeviceAddN"Nadam/gradients/AddN_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y§Ä7Øï?ŠUnknown
]éDeviceMul"	Nadam/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÀ/Ğ²zØï?ŠUnknown
_êDeviceMul"Nadam/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yk¸Û-íØï?ŠUnknown
_ëDeviceMul"Nadam/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YAç¨_Ùï?ŠUnknown
_ìDeviceMul"Nadam/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÁÉò#ÒÙï?ŠUnknown
_íDeviceMul"Nadam/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YlRşDÚï?ŠUnknown
_îDeviceMul"Nadam/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÛ	·Úï?ŠUnknown
_ïDeviceMul"Nadam/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÂc•)Ûï?ŠUnknown
_ğDeviceMul"Nadam/mul_7(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ymì œÛï?ŠUnknown
]ñDeviceSub"	Nadam/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yu,‹Üï?ŠUnknown
_òDeviceSub"Nadam/sub_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÃı7Üï?ŠUnknown
_óDeviceSub"Nadam/sub_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yn†CóÜï?ŠUnknown
_ôDeviceSub"Nadam/sub_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YOüeİï?ŠUnknown
_õDeviceSub"Nadam/sub_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÄ—ZwØİï?ŠUnknown
_öDeviceSub"Nadam/sub_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yo fòJŞï?ŠUnknown
_÷DeviceSub"Nadam/sub_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y©qm½Şï?ŠUnknown
_øDeviceSub"Nadam/sub_7(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÅ1}è/ßï?ŠUnknown
eùDeviceDivNoNan"div_no_nan_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ypºˆc¢ßï?ŠUnknown
zúDeviceCast"%gradient_tape/mean_squared_error/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YC”Şàï?ŠUnknown
xûDeviceMul"$gradient_tape/mean_squared_error/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÆËŸY‡àï?ŠUnknown
züDeviceMul"&gradient_tape/mean_squared_error/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YqT«Ôùàï?ŠUnknown
xıDeviceSub"$gradient_tape/mean_squared_error/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yİ¶Oláï?ŠUnknown
 şDevice	RsqrtGrad"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/RsqrtGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÇeÂÊŞáï?ŠUnknown
˜ÿDeviceMul"Dgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YrîÍEQâï?ŠUnknown
œ€DeviceMul"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_1/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YwÙÀÃâï?ŠUnknown
œDeviceMul"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_2/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÈÿä;6ãï?ŠUnknown
”‚DeviceCast"?gradient_tape/sequential_23/batch_normalization_46/moments/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ysˆğ¶¨ãï?ŠUnknown
’ƒDeviceMul">gradient_tape/sequential_23/batch_normalization_46/moments/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yü1äï?ŠUnknown
”„DeviceMul"@gradient_tape/sequential_23/batch_normalization_46/moments/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÉ™­äï?ŠUnknown
 …Device	RsqrtGrad"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/RsqrtGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yt"( åï?ŠUnknown
˜†DeviceMul"Dgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y«£råï?ŠUnknown
š‡DeviceMul"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÊ3*ååï?ŠUnknown
œˆDeviceMul"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_1/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yu¼5™Wæï?ŠUnknown
œ‰DeviceSum"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y EAÊæï?ŠUnknown
œŠDeviceMul"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_2/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YËÍL<çï?ŠUnknown
˜‹DeviceNeg"Dgradient_tape/sequential_23/batch_normalization_47/batchnorm/sub/Neg(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YvVX
¯çï?ŠUnknown
–ŒDeviceCast"Agradient_tape/sequential_23/batch_normalization_47/moments/Cast_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y!ßc…!èï?ŠUnknown
’DeviceMul">gradient_tape/sequential_23/batch_normalization_47/moments/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÌgo ”èï?ŠUnknown
”DeviceMul"@gradient_tape/sequential_23/batch_normalization_47/moments/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Ywğz{éï?ŠUnknown
œDeviceRealDiv"Dgradient_tape/sequential_23/batch_normalization_47/moments/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y"y†öxéï?ŠUnknown
„DeviceEluGrad",gradient_tape/sequential_23/dense_69/EluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÍ’qëéï?ŠUnknown
†‘DeviceSquaredDifference"$mean_squared_error/SquaredDifference(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YxŠì]êï?ŠUnknown
x’DeviceSum"$mean_squared_error/weighted_loss/Sum(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y#©gĞêï?ŠUnknown
‡“DeviceCast"2mean_squared_error/weighted_loss/num_elements/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÎ›´âBëï?ŠUnknown
¬”DeviceAssignSubVariableOp"Hsequential_23/batch_normalization_46/AssignMovingAvg/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yy$À]µëï?ŠUnknown
Œ•DeviceMul"8sequential_23/batch_normalization_46/AssignMovingAvg/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y$­ËØ'ìï?ŠUnknown
Œ–DeviceSub"8sequential_23/batch_normalization_46/AssignMovingAvg/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÏ5×Sšìï?ŠUnknown
®—DeviceAssignSubVariableOp"Jsequential_23/batch_normalization_46/AssignMovingAvg_1/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Yz¾âÎíï?ŠUnknown
˜DeviceMul":sequential_23/batch_normalization_46/AssignMovingAvg_1/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y%GîIíï?ŠUnknown
™DeviceSub":sequential_23/batch_normalization_46/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YĞÏùÄñíï?ŠUnknown
ŠšDeviceRsqrt"4sequential_23/batch_normalization_46/batchnorm/Rsqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y{X@dîï?ŠUnknown
ˆ›DeviceAddV2"2sequential_23/batch_normalization_46/batchnorm/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y&á»Öîï?ŠUnknown
†œDeviceMul"2sequential_23/batch_normalization_46/batchnorm/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÑi6Iïï?ŠUnknown
ˆDeviceMul"4sequential_23/batch_normalization_46/batchnorm/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y|ò'±»ïï?ŠUnknown
¬DeviceAssignSubVariableOp"Hsequential_23/batch_normalization_47/AssignMovingAvg/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y'{3,.ğï?ŠUnknown
ŒŸDeviceSub"8sequential_23/batch_normalization_47/AssignMovingAvg/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÒ?§ ğï?ŠUnknown
® DeviceAssignSubVariableOp"Jsequential_23/batch_normalization_47/AssignMovingAvg_1/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y}ŒJ"ñï?ŠUnknown
¡DeviceMul":sequential_23/batch_normalization_47/AssignMovingAvg_1/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y(V…ñï?ŠUnknown
¢DeviceSub":sequential_23/batch_normalization_47/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÓaøñï?ŠUnknown
Š£DeviceRsqrt"4sequential_23/batch_normalization_47/batchnorm/Rsqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y~&m“jòï?ŠUnknown
†¤DeviceMul"2sequential_23/batch_normalization_47/batchnorm/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y)¯xİòï?ŠUnknown
ˆ¥DeviceMul"4sequential_23/batch_normalization_47/batchnorm/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÔ7„‰Oóï?ŠUnknown
†¦DeviceSub"2sequential_23/batch_normalization_47/batchnorm/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÀÂóï?ŠUnknown
n§DeviceElu"sequential_23/dense_70/Elu(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?Y*I›4ôï?ŠUnknown
v¨DeviceBiasAdd"sequential_23/dense_71/BiasAdd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Qùß*âÂ?YÕÑ¦ú¦ôï?ŠUnknown
n©DeviceMul"Nadam/Nadam/update_6/mul_2(1R¸…ëQ@9R¸…ëQ@AR¸…ëQ@IR¸…ëQ@Q¤mzÚpR?Y¿;jDõï?ŠUnknown
nªDeviceMul"Nadam/Nadam/update_8/mul_4(1R¸…ëQ@9R¸…ëQ@AR¸…ëQ@IR¸…ëQ@Q¤mzÚpR?Y©¥-‰õï?ŠUnknown
ƒ«Device_Recv"-gradient_tape/mean_squared_error/floordiv/_26(1ÓMbX9@9ÓMbX9@AÓMbX9@IÓMbX9@QPHs_P?Yv#oÃçõï?ŠUnknown
l¬DeviceMul"Nadam/Nadam/update/mul_3(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QãZ|ä?YŞ4öï?ŠUnknown
l­DeviceMul"Nadam/Nadam/update_3/mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QãZ|ä?YF“z€öï?ŠUnknown
r®Device_Recv"Nadam/Cast/ReadVariableOp/_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y¸¶šÌÌöï?ŠUnknown
n¯DeviceSqrt"Nadam/Nadam/update_1/Sqrt(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y*g¢÷ï?ŠUnknown
l°DeviceSub"Nadam/Nadam/update_1/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Yœªpe÷ï?ŠUnknown
n±DeviceMul"Nadam/Nadam/update_2/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YÈ±Â±÷ï?ŠUnknown
n²DeviceMul"Nadam/Nadam/update_2/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y€x¹ş÷ï?ŠUnknown
n³DeviceMul"Nadam/Nadam/update_2/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Yò(ÁfJøï?ŠUnknown
n´DeviceMul"Nadam/Nadam/update_3/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YdÙÈ¸–øï?ŠUnknown
nµDeviceMul"Nadam/Nadam/update_3/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YÖ‰Ğ
ãøï?ŠUnknown
p¶DeviceAddV2"Nadam/Nadam/update_5/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YH:Ø\/ùï?ŠUnknown
l·DeviceMul"Nadam/Nadam/update_5/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Yºêß®{ùï?ŠUnknown
n¸DeviceMul"Nadam/Nadam/update_5/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y,›ç Èùï?ŠUnknown
n¹DeviceMul"Nadam/Nadam/update_5/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YKïRúï?ŠUnknown
lºDeviceMul"Nadam/Nadam/update_6/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Yüö¤`úï?ŠUnknown
n»DeviceMul"Nadam/Nadam/update_6/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y‚¬şö¬úï?ŠUnknown
l¼DeviceSub"Nadam/Nadam/update_6/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Yô\Iùúï?ŠUnknown
n½DeviceMul"Nadam/Nadam/update_7/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Yf›Eûï?ŠUnknown
p¾DeviceAddV2"Nadam/Nadam/update_9/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YØ½í‘ûï?ŠUnknown
p¿DeviceAddV2"Nadam/Nadam/update_9/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YJn?Şûï?ŠUnknown
nÀDeviceMul"Nadam/Nadam/update_9/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y¼%‘*üï?ŠUnknown
tÁDeviceRealDiv"Nadam/Nadam/update_9/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y.Ï,ãvüï?ŠUnknown
€ÂDevice_Recv"*gradient_tape/mean_squared_error/Shape/_20(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y 45Ãüï?ŠUnknown
šÃDeviceMul"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y0<‡ıï?ŠUnknown
šÄDeviceMul"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?Y„àCÙ[ıï?ŠUnknown
–ÅDeviceCast"Agradient_tape/sequential_23/batch_normalization_46/moments/Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YöK+¨ıï?ŠUnknown
šÆDeviceMul"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YhAS}ôıï?ŠUnknown
ÇDevice_Recv"Ggradient_tape/sequential_23/batch_normalization_47/moments/floordiv/_16(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YÚñZÏ@şï?ŠUnknown
ŸÈDevice_Recv"Igradient_tape/sequential_23/batch_normalization_47/moments/floordiv_1/_14(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QQ•ì?YL¢b!şï?ŠUnknown
ŒÉDevice	_HostRecv"2gradient_tape/mean_squared_error/DynamicStitch/_28(1ÙÎ÷Sã¥û?9ÙÎ÷Sã¥û?AÙÎ÷Sã¥û?IÙÎ÷Sã¥û?Qü8ŸM ?Y,™†Íşï?ŠUnknown
ÊDevice_Recv"Ggradient_tape/sequential_23/batch_normalization_46/moments/floordiv/_12(1L7‰A`åğ?9L7‰A`åğ?AL7‰A`åğ?IL7‰A`åğ?Qûy}û%­ó>Y'åàôşï?ŠUnknown
hËDevice_Recv"IteratorGetNext/_4(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>Y`îè	ÿï?ŠUnknown
hÌDevice_Recv"IteratorGetNext/_6(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>Y™Æì2Aÿï?ŠUnknown
^ÍDevice_Recv"Size/_18(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>YÒğ[gÿï?ŠUnknown
ÎDevice_Recv")gradient_tape/mean_squared_error/Fill/_22(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>Ywô„ÿï?ŠUnknown
ÏDevice_Recv"+gradient_tape/mean_squared_error/Prod_1/_24(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>YDOø­³ÿï?ŠUnknown
ŸĞDevice_Recv"Igradient_tape/sequential_23/batch_normalization_46/moments/floordiv_1/_10(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>Y}'üÖÙÿï?ŠUnknown
fÑDevice_Recv"strided_slice/_8(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QQ•ìó>Y¶ÿÿÿÿÿï?ŠUnknown
CÒHostIDLE"IDLE1Ãõ(\OwÀ@AÃõ(\OwÀ@agÅJWP¶å?igÅJWP¶å?ŠUnknown
vÓHostFlushSummaryWriter"FlushSummaryWriter(1/İ$U­@9/İ$U­@A/İ$U­@I/İ$U­@a‘”×yWÓ?i°6Óaï?ŠUnknown
fÔHost
LogicalAnd"
LogicalAnd(1é&1¬TP@9é&1¬TP@Aé&1¬TP@Ié&1¬TP@aX™Ş£ˆu?ißÁó[äŒï?ŠUnknown
jÕHostWriteSummary"WriteSummary(1V-BK@9V-BK@AV-BK@IV-BK@apÑÅi·øq?i‚MÇÊÕ°ï?ŠUnknown
‹ÖHostDataset"5Iterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat(1‰A`åĞ"7@9‰A`åĞ"7@A?5^ºIL3@I?5^ºIL3@aQ
zWErY?i‡
sí½ï?ŠUnknown
e×HostDataset"Iterator::Model(1–C‹lçkA@9–C‹lçkA@A“V­1@I“V­1@aäiyÏ¾NW?i<ÇÚL6Éï?ŠUnknown
tØHostDataset"Iterator::Model::ParallelMapV2(1˜nƒÀ*1@9˜nƒÀ*1@A˜nƒÀ*1@I˜nƒÀ*1@a²X¾"í¢V?ih&lÃ‡Ôï?ŠUnknown
•ÙHostDataset"?Iterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate(1çû©ñÒ4@9çû©ñÒ4@Amçû©ñÒ)@Imçû©ñÒ)@aÈ[¢™Q?ig=İï?ŠUnknown
_ÚHostGatherV2"GatherV2(1 /İ$†)@9 /İ$†)@A /İ$†)@I /İ$†)@aäÊTA÷ÓP?i{Şuåï?ŠUnknown
aÛHostGatherV2"
GatherV2_1(1!°rh‘í!@9!°rh‘í!@A!°rh‘í!@I!°rh‘í!@aòÍ¯›Ï£G?inıÄÿ]ëï?ŠUnknown
¥ÜHostDataset"OIterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate[0]::TensorSlice(1Å °rh‘@9Å °rh‘@AÅ °rh‘@IÅ °rh‘@a¥Ğ`L'D?i¢ÉÒgğï?ŠUnknown
yİHostDataset"#Iterator::Model::ParallelMapV2::Zip(1{®Gá*I@9{®Gá*I@A-²ï§@I-²ï§@aC—»®<;?iÍ‹hÏóï?ŠUnknown
vŞHostReadVariableOp"Nadam/Cast/ReadVariableOp(1sh‘í|¿@9sh‘í|¿@Ash‘í|¿@Ish‘í|¿@a;k„ã|6?i¢=(’öï?ŠUnknown
mßHostIteratorGetNext"IteratorGetNext(1Zd;ßO@9Zd;ßO@AZd;ßO@IZd;ßO@aîÃŞ¤4?id» ´&ùï?ŠUnknown
—àHostDataset"AIterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat::FromTensor(1NbX9´@9NbX9´ş?ANbX9´@INbX9´ş?aÁ²¼W@>4?iú²|®ûï?ŠUnknown
fáHost_Send"IteratorGetNext/_3(1V-²ı?9V-²ı?AV-²ı?IV-²ı?a§êO¿”#?iù§÷½çüï?ŠUnknown
pâHost_Send"Nadam/Cast/ReadVariableOp/_1(1=
×£p=ü?9=
×£p=ü?A=
×£p=ü?I=
×£p=ü?aÕW–ÿ_"?i^¡÷£şï?ŠUnknown
…ãHostDataset"/Iterator::Model::ParallelMapV2::Zip[0]::FlatMap(1)\Âõ6@9)\Âõ6@AV-²÷?IV-²÷?aË1©OŞ>?i¨êšÿï?ŠUnknown
bäHostIdentity"Identity(1333333ï?9333333ï?A333333ï?I333333ï?aTÜz÷‘?iï¥*°ÿï?ŠUnknown
fåHost_Send"IteratorGetNext/_5(1ƒÀÊ¡EŞ?9ƒÀÊ¡EŞ?AƒÀÊ¡EŞ?IƒÀÊ¡EŞ?aş\ „Võ?i      ğ?ŠUnknown*°Ò
DeviceMatMul"+gradient_tape/sequential_23/dense_70/MatMul(1ÇK7‰A *@9ÇK7‰A *@AÇK7‰A *@IÇK7‰A *@Qh5ëâÚ‡?Yh5ëâÚ‡?ŠUnknown
sDeviceMatMul"sequential_23/dense_69/MatMul(1ÇK7‰A *@9ÇK7‰A *@AÇK7‰A *@IÇK7‰A *@Qh5ëâÚ‡?Yh5ëâÚ—?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_23/dense_69/MatMul(1ú~j¼t“(@9ú~j¼t“(@Aú~j¼t“(@Iú~j¼t“(@Q¨tQ³†?YŞ÷‰2n¡?ŠUnknown
sDeviceMatMul"sequential_23/dense_70/MatMul(1ú~j¼t“(@9ú~j¼t“(@Aú~j¼t“(@Iú~j¼t“(@Q¨tQ³†?YUËï¦?ŠUnknown
mDeviceMul"Nadam/Nadam/update_3/mul_2(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@QD  íù.„?YUf‘‰û«?ŠUnknown
ƒDeviceMatMul"-gradient_tape/sequential_23/dense_70/MatMul_1(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@QD  íù.„?Y•*W¤ƒ°?ŠUnknown
‹DeviceDynamicStitch".gradient_tape/mean_squared_error/DynamicStitch(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Qo]´Ğ&°y?Ylpbs¦²?ŠUnknown
“DeviceBiasAddGrad"8gradient_tape/sequential_23/dense_71/BiasAdd/BiasAddGrad(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Qo]´Ğ&°y?YC¶mà¨¹³?ŠUnknown
ƒ	DeviceMatMul"-gradient_tape/sequential_23/dense_71/MatMul_1(1yé&1¬@9yé&1¬@Ayé&1¬@Iyé&1¬@Qo]´Ğ&°y?YüxM«Tµ?ŠUnknown
s
DeviceMatMul"sequential_23/dense_71/MatMul(1NbX9´@9NbX9´@ANbX9´@INbX9´@Qî‹d("v?YÙDÿ?Ì¶¶?ŠUnknown
ŸDeviceSquaredDifference">sequential_23/batch_normalization_46/moments/SquaredDifference(1®Gáz”@9®Gáz”@A®Gáz”@I®Gáz”@Qb"kv?Y¯e±&&¸?ŠUnknown
gDevice
LogicalAnd"
LogicalAnd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³v?Yú|–_qw¹?ŠUnknown
^DeviceCast"
Nadam/Cast(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?Y¸eUdº?ŠUnknown
qDeviceRealDiv"Nadam/Nadam/update/truediv(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?YvNi™Â»?ŠUnknown
‰DeviceTile"5gradient_tape/mean_squared_error/weighted_loss/Tile_1(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?Y47Óm-è¼?ŠUnknown
‘DeviceSub">gradient_tape/sequential_23/batch_normalization_46/moments/sub(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?Yò’rÁ¾?ŠUnknown
›DeviceSum"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/add_1/Sum_1(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?Y°QwU3¿?ŠUnknown
™DeviceMul"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_1/Mul(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?Y·ø¾t,À?ŠUnknown
“DeviceBiasAddGrad"8gradient_tape/sequential_23/dense_70/BiasAdd/BiasAddGrad(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?YmgÀ>¿À?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_23/dense_71/MatMul(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?YuáÆÂRÁ?ŠUnknown
…DeviceMean"1sequential_23/batch_normalization_46/moments/mean(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?YÔU&ÅÒäÁ?ŠUnknown
ŸDeviceSquaredDifference">sequential_23/batch_normalization_47/moments/SquaredDifference(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Qá‹îK@Yr?Y3Ê…ÇœwÂ?ŠUnknown
‰DeviceAddV2"4sequential_23/batch_normalization_46/batchnorm/add_1(1'1¬Z@9'1¬Z@A'1¬Z@I'1¬Z@Q›tÛ±ä;r?YØ¥í{	Ã?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_2(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@Qªw¸Ìo]m?Y·‡G¬ñ~Ã?ŠUnknown
uDeviceRealDiv"Nadam/Nadam/update_8/truediv_3(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@Qªw¸Ìo]m?Y–izkgôÃ?ŠUnknown
¡DeviceBroadcastTo"Fgradient_tape/sequential_23/batch_normalization_46/moments/BroadcastTo(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@Qªw¸Ìo]m?YuK­*İiÄ?ŠUnknown
™DeviceRealDiv"Bgradient_tape/sequential_23/batch_normalization_46/moments/truediv(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@Qªw¸Ìo]m?YT-àéRßÄ?ŠUnknown
ƒDeviceEluGrad",gradient_tape/sequential_23/dense_70/EluGrad(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@Qªw¸Ìo]m?Y3©ÈTÅ?ŠUnknown
kDeviceSqrt"Nadam/Nadam/update/Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YLl_7ÊÅ?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YeÉ«y¥?Æ?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y~&øáµÆ?ŠUnknown
u DeviceRealDiv"Nadam/Nadam/update_1/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y—ƒDJ‚*Ç?ŠUnknown
m!DeviceMul"Nadam/Nadam/update_2/mul_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y°à²ğŸÇ?ŠUnknown
s"DeviceRealDiv"Nadam/Nadam/update_2/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÉ=İ_È?ŠUnknown
u#DeviceRealDiv"Nadam/Nadam/update_3/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yâš)ƒÍŠÈ?ŠUnknown
m$DeviceSqrt"Nadam/Nadam/update_4/Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yû÷uë; É?ŠUnknown
o%DeviceAddV2"Nadam/Nadam/update_4/add_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YUÂSªuÉ?ŠUnknown
k&DeviceMul"Nadam/Nadam/update_4/mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y-²¼ëÉ?ŠUnknown
m'DeviceMul"Nadam/Nadam/update_4/mul_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YF[$‡`Ê?ŠUnknown
m(DeviceMul"Nadam/Nadam/update_4/mul_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y_l§ŒõÕÊ?ŠUnknown
m)DeviceMul"Nadam/Nadam/update_4/mul_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YxÉóôcKË?ŠUnknown
m*DeviceMul"Nadam/Nadam/update_4/mul_4(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y‘&@]ÒÀË?ŠUnknown
k+DeviceSub"Nadam/Nadam/update_4/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YªƒŒÅ@6Ì?ŠUnknown
s,DeviceRealDiv"Nadam/Nadam/update_4/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÃàØ-¯«Ì?ŠUnknown
u-DeviceRealDiv"Nadam/Nadam/update_4/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÜ=%–!Í?ŠUnknown
u.DeviceRealDiv"Nadam/Nadam/update_4/truediv_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yõšqş‹–Í?ŠUnknown
u/DeviceRealDiv"Nadam/Nadam/update_4/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yø½fúÎ?ŠUnknown
s0DeviceRealDiv"Nadam/Nadam/update_5/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y'U
ÏhÎ?ŠUnknown
u1DeviceRealDiv"Nadam/Nadam/update_5/truediv_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y@²V7×öÎ?ŠUnknown
u2DeviceRealDiv"Nadam/Nadam/update_5/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YY£ŸElÏ?ŠUnknown
u3DeviceRealDiv"Nadam/Nadam/update_6/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yrlï´áÏ?ŠUnknown
u4DeviceRealDiv"Nadam/Nadam/update_7/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÅä8‘+Ğ?ŠUnknown
s5DeviceRealDiv"Nadam/Nadam/update_8/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YQDlHfĞ?ŠUnknown
^6DevicePow"Nadam/Pow_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YİAj ÿ Ğ?ŠUnknown
j7DeviceAddN"Nadam/gradients/AddN_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YipÔ¶ÛĞ?ŠUnknown
j8DeviceAddN"Nadam/gradients/AddN_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yõ¶nÑ?ŠUnknown
X9DeviceSqrt"Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÍÜ<%QÑ?ŠUnknown
X:DeviceSum"Sum_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YüqÜ‹Ñ?ŠUnknown
;DeviceRealDiv"(gradient_tape/mean_squared_error/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y™*)¥“ÆÑ?ŠUnknown
—<DeviceDivNoNan"?gradient_tape/mean_squared_error/weighted_loss/value/div_no_nan(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y%YOÙJÒ?ŠUnknown
›=DeviceSum"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/add_1/Sum_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y±‡u<Ò?ŠUnknown
™>DeviceMul"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_1/Mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y=¶›A¹vÒ?ŠUnknown
›?DeviceSum"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_1/Sum_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÉäÁup±Ò?ŠUnknown
£@DeviceBroadcastTo"Hgradient_tape/sequential_23/batch_normalization_46/moments/BroadcastTo_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YUè©'ìÒ?ŠUnknown
›ADeviceRealDiv"Dgradient_tape/sequential_23/batch_normalization_46/moments/truediv_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YáAŞŞ&Ó?ŠUnknown
¡BDeviceBroadcastTo"Fgradient_tape/sequential_23/batch_normalization_47/moments/BroadcastTo(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Ymp4–aÓ?ŠUnknown
£CDeviceBroadcastTo"Hgradient_tape/sequential_23/batch_normalization_47/moments/BroadcastTo_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YùZFMœÓ?ŠUnknown
‘DDeviceSub">gradient_tape/sequential_23/batch_normalization_47/moments/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y…Í€z×Ó?ŠUnknown
™EDeviceRealDiv"Bgradient_tape/sequential_23/batch_normalization_47/moments/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yü¦®»Ô?ŠUnknown
“FDeviceBiasAddGrad"8gradient_tape/sequential_23/dense_69/BiasAdd/BiasAddGrad(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y*ÍârLÔ?ŠUnknown
‡GDeviceMul"4sequential_23/batch_normalization_46/batchnorm/mul_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y)Yó*‡Ô?ŠUnknown
…HDeviceSub"2sequential_23/batch_normalization_46/batchnorm/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yµ‡KáÁÔ?ŠUnknown
‰IDeviceMean"5sequential_23/batch_normalization_46/moments/variance(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YA¶?˜üÔ?ŠUnknown
‡JDeviceAddV2"2sequential_23/batch_normalization_47/batchnorm/add(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YÍäe³O7Õ?ŠUnknown
‰KDeviceAddV2"4sequential_23/batch_normalization_47/batchnorm/add_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YYŒçrÕ?ŠUnknown
‡LDeviceMul"4sequential_23/batch_normalization_47/batchnorm/mul_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YåA²¾¬Õ?ŠUnknown
…MDeviceMean"1sequential_23/batch_normalization_47/moments/mean(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YqpØOuçÕ?ŠUnknown
‰NDeviceMean"5sequential_23/batch_normalization_47/moments/variance(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Yışƒ,"Ö?ŠUnknown
uODeviceBiasAdd"sequential_23/dense_69/BiasAdd(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?Y‰Í$¸ã\Ö?ŠUnknown
mPDeviceElu"sequential_23/dense_69/Elu(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Q5Fš[m?YüJìš—Ö?ŠUnknown
~QDeviceDivNoNan"&mean_squared_error/weighted_loss/value(1¨ÆK7‰A@9¨ÆK7‰A@A¨ÆK7‰A@I¨ÆK7‰A@Q©ñŞâ m?YDŞ²ÜÑÖ?ŠUnknown
uRDeviceRealDiv"Nadam/Nadam/update_9/truediv_3(1¢E¶óıÔ@9¢E¶óıÔ@A¢E¶óıÔ@I¢E¶óıÔ@Q4£wÂj?f?YŠÍ‡[şÖ?ŠUnknown
xSDeviceAssignAddVariableOp"AssignAddVariableOp_3(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YÖ²šh*×?ŠUnknown
oTDeviceSquare"Nadam/Nadam/update/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y"˜­¬uV×?ŠUnknown
mUDeviceAddV2"Nadam/Nadam/update/add_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Yn}=¿‚‚×?ŠUnknown
iVDeviceMul"Nadam/Nadam/update/mul(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YºbÍÑ®×?ŠUnknown
qWDeviceSquare"Nadam/Nadam/update_1/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YH]äœÚ×?ŠUnknown
oXDeviceAddV2"Nadam/Nadam/update_1/add_1(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YR-íö©Ø?ŠUnknown
kYDeviceSub"Nadam/Nadam/update_2/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y}	·2Ø?ŠUnknown
qZDeviceSquare"Nadam/Nadam/update_3/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Yê÷Ä^Ø?ŠUnknown
m[DeviceMul"Nadam/Nadam/update_3/mul_3(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y6İœ.ÑŠØ?ŠUnknown
q\DeviceSquare"Nadam/Nadam/update_4/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y‚Â,AŞ¶Ø?ŠUnknown
o]DeviceAddV2"Nadam/Nadam/update_4/add_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YÎ§¼SëâØ?ŠUnknown
q^DeviceSquare"Nadam/Nadam/update_5/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YLføÙ?ŠUnknown
o_DeviceAddV2"Nadam/Nadam/update_5/add_1(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YfrÜx;Ù?ŠUnknown
m`DeviceMul"Nadam/Nadam/update_5/mul_6(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y²Wl‹gÙ?ŠUnknown
maDeviceMul"Nadam/Nadam/update_6/mul_3(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Yş<ü“Ù?ŠUnknown
mbDeviceMul"Nadam/Nadam/update_6/mul_6(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YJ"Œ°,¿Ù?ŠUnknown
mcDeviceMul"Nadam/Nadam/update_7/mul_1(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y–Ã9ëÙ?ŠUnknown
qdDeviceSquare"Nadam/Nadam/update_8/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Yâì«ÕFÚ?ŠUnknown
meDeviceMul"Nadam/Nadam/update_9/mul_4(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y.Ò;èSCÚ?ŠUnknown
ufDeviceRealDiv"Nadam/Nadam/update_9/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Yz·Ëú`oÚ?ŠUnknown
bgDeviceDivNoNan"
div_no_nan(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YÆœ[n›Ú?ŠUnknown
—hDeviceNeg"Dgradient_tape/sequential_23/batch_normalization_46/batchnorm/sub/Neg(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y‚ë{ÇÚ?ŠUnknown
“iDeviceCast"?gradient_tape/sequential_23/batch_normalization_47/moments/Cast(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Y^g{2ˆóÚ?ŠUnknown
‹jDeviceMul"8sequential_23/batch_normalization_47/AssignMovingAvg/mul(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?YªLE•Û?ŠUnknown
ukDeviceBiasAdd"sequential_23/dense_70/BiasAdd(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q¦òG‰f?Yö1›W¢KÛ?ŠUnknown
vlDeviceAssignAddVariableOp"AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YßÔ·¾«wÛ?ŠUnknown
xmDeviceAssignAddVariableOp"AssignAddVariableOp_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÈwÔ%µ£Û?ŠUnknown
xnDeviceAssignAddVariableOp"AssignAddVariableOp_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y±ñŒ¾ÏÛ?ŠUnknown
xoDeviceAssignAddVariableOp"AssignAddVariableOp_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yš½ôÇûÛ?ŠUnknown
XpDeviceCast"Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yƒ`*[Ñ'Ü?ŠUnknown
ZqDeviceCast"Cast_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YlGÂÚSÜ?ŠUnknown
VrDeviceMul"Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YU¦c)äÜ?ŠUnknown
`sDeviceCast"Nadam/Cast_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y>I€í«Ü?ŠUnknown
`tDeviceCast"Nadam/Cast_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y'ìœ÷ö×Ü?ŠUnknown
‚uDeviceAssignAddVariableOp"Nadam/Nadam/AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¹^ İ?ŠUnknown
kvDeviceAddV2"Nadam/Nadam/update/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yù1ÖÅ	0İ?ŠUnknown
mwDeviceAddV2"Nadam/Nadam/update/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YâÔò,\İ?ŠUnknown
mxDeviceAddV2"Nadam/Nadam/update/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YËw”ˆİ?ŠUnknown
kyDeviceMul"Nadam/Nadam/update/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y´,û%´İ?ŠUnknown
kzDeviceMul"Nadam/Nadam/update/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y½Hb/àİ?ŠUnknown
k{DeviceMul"Nadam/Nadam/update/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y†`eÉ8Ş?ŠUnknown
k|DeviceMul"Nadam/Nadam/update/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yo‚0B8Ş?ŠUnknown
k}DeviceMul"Nadam/Nadam/update/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YX¦—KdŞ?ŠUnknown
i~DeviceSub"Nadam/Nadam/update/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YAI»şTŞ?ŠUnknown
mDeviceAddV2"Nadam/Nadam/update_1/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y*ì×e^¼Ş?ŠUnknown
p€DeviceAddV2"Nadam/Nadam/update_1/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YôÌgèŞ?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_1/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yü14qß?ŠUnknown
l‚DeviceMul"Nadam/Nadam/update_1/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YåÔ-›z@ß?ŠUnknown
nƒDeviceMul"Nadam/Nadam/update_1/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÎwJ„lß?ŠUnknown
n„DeviceMul"Nadam/Nadam/update_1/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y·gi˜ß?ŠUnknown
n…DeviceMul"Nadam/Nadam/update_1/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y ½ƒĞ–Äß?ŠUnknown
n†DeviceMul"Nadam/Nadam/update_1/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‰` 7 ğß?ŠUnknown
n‡DeviceMul"Nadam/Nadam/update_1/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¹^ÏTà?ŠUnknown
nˆDeviceMul"Nadam/Nadam/update_1/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y.Óì‚Y$à?ŠUnknown
t‰DeviceRealDiv"Nadam/Nadam/update_1/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y£${6^:à?ŠUnknown
vŠDeviceRealDiv"Nadam/Nadam/update_1/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yv	êbPà?ŠUnknown
v‹DeviceRealDiv"Nadam/Nadam/update_1/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÇ—gfà?ŠUnknown
nŒDeviceSqrt"Nadam/Nadam/update_2/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y&Ql|à?ŠUnknown
rDeviceSquare"Nadam/Nadam/update_2/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Ywj´q’à?ŠUnknown
nDeviceAddV2"Nadam/Nadam/update_2/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yì»B¸u¨à?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_2/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YaÑkz¾à?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_2/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÖ^_Ôà?ŠUnknown
p‘DeviceAddV2"Nadam/Nadam/update_2/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YK°íÒƒêà?ŠUnknown
l’DeviceMul"Nadam/Nadam/update_2/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÀ|†ˆ á?ŠUnknown
n“DeviceMul"Nadam/Nadam/update_2/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y5S
:á?ŠUnknown
n”DeviceMul"Nadam/Nadam/update_2/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yª¤˜í‘,á?ŠUnknown
v•DeviceRealDiv"Nadam/Nadam/update_2/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yö&¡–Bá?ŠUnknown
v–DeviceRealDiv"Nadam/Nadam/update_2/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y”GµT›Xá?ŠUnknown
v—DeviceRealDiv"Nadam/Nadam/update_2/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y	™C ná?ŠUnknown
n˜DeviceSqrt"Nadam/Nadam/update_3/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y~êÑ»¤„á?ŠUnknown
n™DeviceAddV2"Nadam/Nadam/update_3/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yó;`o©šá?ŠUnknown
pšDeviceAddV2"Nadam/Nadam/update_3/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yhî"®°á?ŠUnknown
p›DeviceAddV2"Nadam/Nadam/update_3/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YİŞ|Ö²Æá?ŠUnknown
pœDeviceAddV2"Nadam/Nadam/update_3/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YR0Š·Üá?ŠUnknown
nDeviceMul"Nadam/Nadam/update_3/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÇ™=¼òá?ŠUnknown
nDeviceMul"Nadam/Nadam/update_3/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y<Ó'ñÀâ?ŠUnknown
lŸDeviceSub"Nadam/Nadam/update_3/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y±$¶¤Åâ?ŠUnknown
t DeviceRealDiv"Nadam/Nadam/update_3/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y&vDXÊ4â?ŠUnknown
v¡DeviceRealDiv"Nadam/Nadam/update_3/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y›ÇÒÏJâ?ŠUnknown
v¢DeviceRealDiv"Nadam/Nadam/update_3/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Ya¿Ó`â?ŠUnknown
n£DeviceAddV2"Nadam/Nadam/update_4/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y…jïrØvâ?ŠUnknown
p¤DeviceAddV2"Nadam/Nadam/update_4/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yú»}&İŒâ?ŠUnknown
n¥DeviceMul"Nadam/Nadam/update_4/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YoÚá¢â?ŠUnknown
n¦DeviceMul"Nadam/Nadam/update_4/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yä^šæ¸â?ŠUnknown
n§DeviceSqrt"Nadam/Nadam/update_5/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YY°(AëÎâ?ŠUnknown
n¨DeviceAddV2"Nadam/Nadam/update_5/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÎ·ôïäâ?ŠUnknown
p©DeviceAddV2"Nadam/Nadam/update_5/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YCSE¨ôúâ?ŠUnknown
nªDeviceMul"Nadam/Nadam/update_5/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¸¤Ó[ùã?ŠUnknown
n«DeviceMul"Nadam/Nadam/update_5/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y-öaş&ã?ŠUnknown
n¬DeviceMul"Nadam/Nadam/update_5/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¢GğÂ=ã?ŠUnknown
l­DeviceSub"Nadam/Nadam/update_5/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y™~vSã?ŠUnknown
v®DeviceRealDiv"Nadam/Nadam/update_5/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YŒê*iã?ŠUnknown
n¯DeviceSqrt"Nadam/Nadam/update_6/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y<›İã?ŠUnknown
r°DeviceSquare"Nadam/Nadam/update_6/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yv)‘•ã?ŠUnknown
n±DeviceAddV2"Nadam/Nadam/update_6/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YëŞ·D«ã?ŠUnknown
p²DeviceAddV2"Nadam/Nadam/update_6/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y`0FøÁã?ŠUnknown
p³DeviceAddV2"Nadam/Nadam/update_6/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÕÔ«#×ã?ŠUnknown
p´DeviceAddV2"Nadam/Nadam/update_6/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YJÓb_(íã?ŠUnknown
nµDeviceMul"Nadam/Nadam/update_6/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¿$ñ-ä?ŠUnknown
n¶DeviceMul"Nadam/Nadam/update_6/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y4vÆ1ä?ŠUnknown
t·DeviceRealDiv"Nadam/Nadam/update_6/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y©Çz6/ä?ŠUnknown
v¸DeviceRealDiv"Nadam/Nadam/update_6/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yœ-;Eä?ŠUnknown
v¹DeviceRealDiv"Nadam/Nadam/update_6/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y“j*á?[ä?ŠUnknown
nºDeviceSqrt"Nadam/Nadam/update_7/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¼¸”Dqä?ŠUnknown
r»DeviceSquare"Nadam/Nadam/update_7/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y}GHI‡ä?ŠUnknown
n¼DeviceAddV2"Nadam/Nadam/update_7/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yò^ÕûMä?ŠUnknown
p½DeviceAddV2"Nadam/Nadam/update_7/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yg°c¯R³ä?ŠUnknown
p¾DeviceAddV2"Nadam/Nadam/update_7/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÜòbWÉä?ŠUnknown
p¿DeviceAddV2"Nadam/Nadam/update_7/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YQS€\ßä?ŠUnknown
lÀDeviceMul"Nadam/Nadam/update_7/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÆ¤Ê`õä?ŠUnknown
nÁDeviceMul"Nadam/Nadam/update_7/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y;öœ}eå?ŠUnknown
nÂDeviceMul"Nadam/Nadam/update_7/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y°G+1j!å?ŠUnknown
nÃDeviceMul"Nadam/Nadam/update_7/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y%™¹än7å?ŠUnknown
nÄDeviceMul"Nadam/Nadam/update_7/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YšêG˜sMå?ŠUnknown
lÅDeviceSub"Nadam/Nadam/update_7/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y<ÖKxcå?ŠUnknown
tÆDeviceRealDiv"Nadam/Nadam/update_7/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y„dÿ|yå?ŠUnknown
vÇDeviceRealDiv"Nadam/Nadam/update_7/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YùŞò²å?ŠUnknown
vÈDeviceRealDiv"Nadam/Nadam/update_7/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yn0f†¥å?ŠUnknown
nÉDeviceSqrt"Nadam/Nadam/update_8/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yã‹»å?ŠUnknown
nÊDeviceAddV2"Nadam/Nadam/update_8/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YXÓÍÑå?ŠUnknown
pËDeviceAddV2"Nadam/Nadam/update_8/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÍ$,”çå?ŠUnknown
pÌDeviceAddV2"Nadam/Nadam/update_8/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YBvº4™ıå?ŠUnknown
pÍDeviceAddV2"Nadam/Nadam/update_8/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y·ÇHèæ?ŠUnknown
lÎDeviceMul"Nadam/Nadam/update_8/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y,×›¢)æ?ŠUnknown
nÏDeviceMul"Nadam/Nadam/update_8/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¡jeO§?æ?ŠUnknown
nĞDeviceMul"Nadam/Nadam/update_8/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¼ó¬Uæ?ŠUnknown
nÑDeviceMul"Nadam/Nadam/update_8/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‹‚¶°kæ?ŠUnknown
nÒDeviceMul"Nadam/Nadam/update_8/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y _jµæ?ŠUnknown
nÓDeviceMul"Nadam/Nadam/update_8/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yu°º—æ?ŠUnknown
lÔDeviceSub"Nadam/Nadam/update_8/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yê-Ñ¾­æ?ŠUnknown
vÕDeviceRealDiv"Nadam/Nadam/update_8/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y_S»„ÃÃæ?ŠUnknown
vÖDeviceRealDiv"Nadam/Nadam/update_8/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÔ¤I8ÈÙæ?ŠUnknown
n×DeviceSqrt"Nadam/Nadam/update_9/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YIö×ëÌïæ?ŠUnknown
rØDeviceSquare"Nadam/Nadam/update_9/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¾GfŸÑç?ŠUnknown
nÙDeviceAddV2"Nadam/Nadam/update_9/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y3™ôRÖç?ŠUnknown
pÚDeviceAddV2"Nadam/Nadam/update_9/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¨ê‚Û1ç?ŠUnknown
lÛDeviceMul"Nadam/Nadam/update_9/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y<ºßGç?ŠUnknown
nÜDeviceMul"Nadam/Nadam/update_9/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y’Ÿmä]ç?ŠUnknown
nİDeviceMul"Nadam/Nadam/update_9/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yß-!ésç?ŠUnknown
nŞDeviceMul"Nadam/Nadam/update_9/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y|0¼Ôí‰ç?ŠUnknown
nßDeviceMul"Nadam/Nadam/update_9/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YñJˆòŸç?ŠUnknown
làDeviceSub"Nadam/Nadam/update_9/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YfÓØ;÷µç?ŠUnknown
váDeviceRealDiv"Nadam/Nadam/update_9/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÛ$gïûËç?ŠUnknown
]âDevicePow"	Nadam/Pow(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YPvõ¢ âç?ŠUnknown
_ãDevicePow"Nadam/Pow_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÅÇƒVøç?ŠUnknown
_äDeviceAddV2"	Nadam/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y:

è?ŠUnknown
aåDeviceAddV2"Nadam/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¯j ½$è?ŠUnknown
iæDeviceAddN"Nadam/gradients/AddN(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y$¼.q:è?ŠUnknown
kçDeviceAddN"Nadam/gradients/AddN_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y™½$Pè?ŠUnknown
]èDeviceMul"	Nadam/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y_KØfè?ŠUnknown
_éDeviceMul"Nadam/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yƒ°Ù‹!|è?ŠUnknown
_êDeviceMul"Nadam/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yøh?&’è?ŠUnknown
_ëDeviceMul"Nadam/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YmSöò*¨è?ŠUnknown
_ìDeviceMul"Nadam/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yâ¤„¦/¾è?ŠUnknown
_íDeviceMul"Nadam/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YWöZ4Ôè?ŠUnknown
_îDeviceMul"Nadam/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÌG¡9êè?ŠUnknown
_ïDeviceMul"Nadam/mul_7(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YA™/Á= é?ŠUnknown
]ğDeviceSub"	Nadam/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¶ê½tBé?ŠUnknown
_ñDeviceSub"Nadam/sub_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y+<L(G,é?ŠUnknown
_òDeviceSub"Nadam/sub_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y ÚÛKBé?ŠUnknown
_óDeviceSub"Nadam/sub_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YßhPXé?ŠUnknown
_ôDeviceSub"Nadam/sub_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YŠ0÷BUné?ŠUnknown
_õDeviceSub"Nadam/sub_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yÿ…öY„é?ŠUnknown
_öDeviceSub"Nadam/sub_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YtÓª^šé?ŠUnknown
_÷DeviceSub"Nadam/sub_7(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yé$¢]c°é?ŠUnknown
eøDeviceDivNoNan"div_no_nan_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y^v0hÆé?ŠUnknown
zùDeviceCast"%gradient_tape/mean_squared_error/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÓÇ¾ÄlÜé?ŠUnknown
xúDeviceMul"$gradient_tape/mean_squared_error/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YHMxqòé?ŠUnknown
zûDeviceMul"&gradient_tape/mean_squared_error/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y½jÛ+vê?ŠUnknown
xüDeviceSub"$gradient_tape/mean_squared_error/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y2¼ißzê?ŠUnknown
 ıDevice	RsqrtGrad"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/RsqrtGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y§ø’4ê?ŠUnknown
˜şDeviceMul"Dgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y_†F„Jê?ŠUnknown
œÿDeviceMul"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_1/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‘°úˆ`ê?ŠUnknown
œ€DeviceMul"Hgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_2/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y£­vê?ŠUnknown
”DeviceCast"?gradient_tape/sequential_23/batch_normalization_46/moments/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y{S1a’Œê?ŠUnknown
’‚DeviceMul">gradient_tape/sequential_23/batch_normalization_46/moments/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yğ¤¿—¢ê?ŠUnknown
”ƒDeviceMul"@gradient_tape/sequential_23/batch_normalization_46/moments/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YeöMÈ›¸ê?ŠUnknown
 „Device	RsqrtGrad"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/RsqrtGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÚGÜ{ Îê?ŠUnknown
˜…DeviceMul"Dgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YO™j/¥äê?ŠUnknown
š†DeviceMul"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÄêøâ©úê?ŠUnknown
œ‡DeviceMul"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_1/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y9<‡–®ë?ŠUnknown
œˆDeviceSum"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y®J³&ë?ŠUnknown
œ‰DeviceMul"Hgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_2/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y#ß£ı·<ë?ŠUnknown
˜ŠDeviceNeg"Dgradient_tape/sequential_23/batch_normalization_47/batchnorm/sub/Neg(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y˜02±¼Rë?ŠUnknown
–‹DeviceCast"Agradient_tape/sequential_23/batch_normalization_47/moments/Cast_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‚ÀdÁhë?ŠUnknown
’ŒDeviceMul">gradient_tape/sequential_23/batch_normalization_47/moments/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‚ÓNÆ~ë?ŠUnknown
”DeviceMul"@gradient_tape/sequential_23/batch_normalization_47/moments/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y÷$İËÊ”ë?ŠUnknown
œDeviceRealDiv"Dgradient_tape/sequential_23/batch_normalization_47/moments/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YlvkÏªë?ŠUnknown
„DeviceEluGrad",gradient_tape/sequential_23/dense_69/EluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YáÇù2ÔÀë?ŠUnknown
†DeviceSquaredDifference"$mean_squared_error/SquaredDifference(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YVˆæØÖë?ŠUnknown
x‘DeviceSum"$mean_squared_error/weighted_loss/Sum(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YËjšİìë?ŠUnknown
‡’DeviceCast"2mean_squared_error/weighted_loss/num_elements/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y@¼¤Mâì?ŠUnknown
¬“DeviceAssignSubVariableOp"Hsequential_23/batch_normalization_46/AssignMovingAvg/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yµ3çì?ŠUnknown
Œ”DeviceMul"8sequential_23/batch_normalization_46/AssignMovingAvg/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y*_Á´ë.ì?ŠUnknown
Œ•DeviceSub"8sequential_23/batch_normalization_46/AssignMovingAvg/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YŸ°OhğDì?ŠUnknown
®–DeviceAssignSubVariableOp"Jsequential_23/batch_normalization_46/AssignMovingAvg_1/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YŞõZì?ŠUnknown
—DeviceMul":sequential_23/batch_normalization_46/AssignMovingAvg_1/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‰SlÏùpì?ŠUnknown
˜DeviceSub":sequential_23/batch_normalization_46/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yş¤ú‚ş†ì?ŠUnknown
Š™DeviceRsqrt"4sequential_23/batch_normalization_46/batchnorm/Rsqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Ysöˆ6ì?ŠUnknown
ˆšDeviceAddV2"2sequential_23/batch_normalization_46/batchnorm/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YèGê³ì?ŠUnknown
†›DeviceMul"2sequential_23/batch_normalization_46/batchnorm/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y]™¥Éì?ŠUnknown
ˆœDeviceMul"4sequential_23/batch_normalization_46/batchnorm/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÒê3Qßì?ŠUnknown
¬DeviceAssignSubVariableOp"Hsequential_23/batch_normalization_47/AssignMovingAvg/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YG<Âõì?ŠUnknown
ŒDeviceSub"8sequential_23/batch_normalization_47/AssignMovingAvg/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¼P¸í?ŠUnknown
®ŸDeviceAssignSubVariableOp"Jsequential_23/batch_normalization_47/AssignMovingAvg_1/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y1ßŞk!í?ŠUnknown
 DeviceMul":sequential_23/batch_normalization_47/AssignMovingAvg_1/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y¦0m$7í?ŠUnknown
¡DeviceSub":sequential_23/batch_normalization_47/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y‚ûÒ(Mí?ŠUnknown
Š¢DeviceRsqrt"4sequential_23/batch_normalization_47/batchnorm/Rsqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÓ‰†-cí?ŠUnknown
†£DeviceMul"2sequential_23/batch_normalization_47/batchnorm/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Y%:2yí?ŠUnknown
ˆ¤DeviceMul"4sequential_23/batch_normalization_47/batchnorm/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?Yzv¦í6í?ŠUnknown
†¥DeviceSub"2sequential_23/batch_normalization_47/batchnorm/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YïÇ4¡;¥í?ŠUnknown
n¦DeviceElu"sequential_23/dense_70/Elu(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YdÃT@»í?ŠUnknown
v§DeviceBiasAdd"sequential_23/dense_71/BiasAdd(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q¨tQ³f?YÙjQEÑí?ŠUnknown
n¨DeviceMul"Nadam/Nadam/update_6/mul_2(1R¸…ëQ@9R¸…ëQ@AR¸…ëQ@IR¸…ëQ@QF+ZüÉe?Y–«çí?ŠUnknown
n©DeviceMul"Nadam/Nadam/update_8/mul_4(1R¸…ëQ@9R¸…ëQ@AR¸…ëQ@IR¸…ëQ@QF+ZüÉe?YeÁÙüí?ŠUnknown
ƒªDevice_Recv"-gradient_tape/mean_squared_error/floordiv/_26(1ÓMbX9@9ÓMbX9@AÓMbX9@IÓMbX9@QU]È‰b?YÂ‰Š÷î?ŠUnknown
l«DeviceMul"Nadam/Nadam/update/mul_3(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @Q©Y†E_]?Y—¶à,§î?ŠUnknown
l¬DeviceMul"Nadam/Nadam/update_3/mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @Q©Y†E_]?Ylã£ÏV,î?ŠUnknown
r­Device_Recv"Nadam/Cast/ReadVariableOp/_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yo­œ;î?ŠUnknown
n®DeviceSqrt"Nadam/Nadam/update_1/Sqrt(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y²ú¶i²Iî?ŠUnknown
l¯DeviceSub"Nadam/Nadam/update_1/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YU†À6`Xî?ŠUnknown
n°DeviceMul"Nadam/Nadam/update_2/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YøÊgî?ŠUnknown
n±DeviceMul"Nadam/Nadam/update_2/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y›ÓĞ»uî?ŠUnknown
n²DeviceMul"Nadam/Nadam/update_2/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y>)İi„î?ŠUnknown
n³DeviceMul"Nadam/Nadam/update_3/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yá´æj“î?ŠUnknown
n´DeviceMul"Nadam/Nadam/update_3/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y„@ğ7Å¡î?ŠUnknown
pµDeviceAddV2"Nadam/Nadam/update_5/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y'Ìùs°î?ŠUnknown
l¶DeviceMul"Nadam/Nadam/update_5/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YÊWÒ ¿î?ŠUnknown
n·DeviceMul"Nadam/Nadam/update_5/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YmãŸÎÍî?ŠUnknown
n¸DeviceMul"Nadam/Nadam/update_5/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yol|Üî?ŠUnknown
l¹DeviceMul"Nadam/Nadam/update_6/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y³ú9*ëî?ŠUnknown
nºDeviceMul"Nadam/Nadam/update_6/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YV†)Øùî?ŠUnknown
l»DeviceSub"Nadam/Nadam/update_6/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yù3Ó…ï?ŠUnknown
n¼DeviceMul"Nadam/Nadam/update_7/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yœ< 3ï?ŠUnknown
p½DeviceAddV2"Nadam/Nadam/update_9/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y?)Fmá%ï?ŠUnknown
p¾DeviceAddV2"Nadam/Nadam/update_9/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yâ´O:4ï?ŠUnknown
n¿DeviceMul"Nadam/Nadam/update_9/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y…@Y=Cï?ŠUnknown
tÀDeviceRealDiv"Nadam/Nadam/update_9/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y(ÌbÔêQï?ŠUnknown
€ÁDevice_Recv"*gradient_tape/mean_squared_error/Shape/_20(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YËWl¡˜`ï?ŠUnknown
šÂDeviceMul"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YnãunFoï?ŠUnknown
šÃDeviceMul"Fgradient_tape/sequential_23/batch_normalization_46/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yo;ô}ï?ŠUnknown
–ÄDeviceCast"Agradient_tape/sequential_23/batch_normalization_46/moments/Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y´úˆ¢Œï?ŠUnknown
šÅDeviceMul"Fgradient_tape/sequential_23/batch_normalization_47/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?YW†’ÕO›ï?ŠUnknown
ÆDevice_Recv"Ggradient_tape/sequential_23/batch_normalization_47/moments/floordiv/_16(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Yúœ¢ı©ï?ŠUnknown
ŸÇDevice_Recv"Igradient_tape/sequential_23/batch_normalization_47/moments/floordiv_1/_14(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Q5Fš[]?Y¥o«¸ï?ŠUnknown
ŒÈDevice	_HostRecv"2gradient_tape/mean_squared_error/DynamicStitch/_28(1ÙÎ÷Sã¥û?9ÙÎ÷Sã¥û?AÙÎ÷Sã¥û?IÙÎ÷Sã¥û?Q=£ JÅX?Yo«¥Åï?ŠUnknown
ÉDevice_Recv"Ggradient_tape/sequential_23/batch_normalization_46/moments/floordiv/_12(1L7‰A`åğ?9L7‰A`åğ?AL7‰A`åğ?IL7‰A`åğ?Qg °ãvFN?Yo—^²ŸÌï?ŠUnknown
hÊDevice_Recv"IteratorGetNext/_4(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?YA]ã˜öÓï?ŠUnknown
hËDevice_Recv"IteratorGetNext/_6(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?Y#hMÛï?ŠUnknown
^ÌDevice_Recv"Size/_18(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?Yåèìe¤âï?ŠUnknown
ÍDevice_Recv")gradient_tape/mean_squared_error/Fill/_22(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?Y·®qLûéï?ŠUnknown
ÎDevice_Recv"+gradient_tape/mean_squared_error/Prod_1/_24(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?Y‰tö2Rñï?ŠUnknown
ŸÏDevice_Recv"Igradient_tape/sequential_23/batch_normalization_46/moments/floordiv_1/_10(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?Y[:{©øï?ŠUnknown
fĞDevice_Recv"strided_slice/_8(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Q5Fš[M?Y     ğ?ŠUnknown
vÑHostFlushSummaryWriter"FlushSummaryWriter(1/İ$U­@9/İ$U­@A/İ$U­@I/İ$U­@aNÈ î?iNÈ î?ŠUnknown
fÒHost
LogicalAnd"
LogicalAnd(1é&1¬TP@9é&1¬TP@Aé&1¬TP@Ié&1¬TP@a´3w¹¾?iŒ`¾Îõ™î?ŠUnknown
jÓHostWriteSummary"WriteSummary(1V-BK@9V-BK@AV-BK@IV-BK@a_«”1ó‹?i•Â	ï?ŠUnknown
‹ÔHostDataset"5Iterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat(1‰A`åĞ"7@9‰A`åĞ"7@A?5^ºIL3@I?5^ºIL3@aä—"œÉs?i><VÍU1ï?ŠUnknown
eÕHostDataset"Iterator::Model(1–C‹lçkA@9–C‹lçkA@A“V­1@I“V­1@a…r.6Ør?i#™Â}•Uï?ŠUnknown
tÖHostDataset"Iterator::Model::ParallelMapV2(1˜nƒÀ*1@9˜nƒÀ*1@A˜nƒÀ*1@I˜nƒÀ*1@a:“U0<šq?iID#öÉxï?ŠUnknown
•×HostDataset"?Iterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate(1çû©ñÒ4@9çû©ñÒ4@Amçû©ñÒ)@Imçû©ñÒ)@aÈóø^¥zj?i==‚›D“ï?ŠUnknown
_ØHostGatherV2"GatherV2(1 /İ$†)@9 /İ$†)@A /İ$†)@I /İ$†)@a,Å;Ôå+j?iyVp­ï?ŠUnknown
aÙHostGatherV2"
GatherV2_1(1!°rh‘í!@9!°rh‘í!@A!°rh‘í!@I!°rh‘í!@aP
:şab?iÒ¿ï?ŠUnknown
¥ÚHostDataset"OIterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate[0]::TensorSlice(1Å °rh‘@9Å °rh‘@AÅ °rh‘@IÅ °rh‘@a’-|íêW_?i#Lu~Ïï?ŠUnknown
yÛHostDataset"#Iterator::Model::ParallelMapV2::Zip(1{®Gá*I@9{®Gá*I@A-²ï§@I-²ï§@aÄ…c©.U?iæıÛ~Úï?ŠUnknown
vÜHostReadVariableOp"Nadam/Cast/ReadVariableOp(1sh‘í|¿@9sh‘í|¿@Ash‘í|¿@Ish‘í|¿@a¸O@,Q?im¥ß«âï?ŠUnknown
mİHostIteratorGetNext"IteratorGetNext(1Zd;ßO@9Zd;ßO@AZd;ßO@IZd;ßO@aŸ'½K›P?i„…l²êï?ŠUnknown
—ŞHostDataset"AIterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat::FromTensor(1NbX9´@9NbX9´ş?ANbX9´@INbX9´ş?aãØ†ë{O?i·e T‘òï?ŠUnknown
fßHost_Send"IteratorGetNext/_3(1V-²ı?9V-²ı?AV-²ı?IV-²ı?a¸yìÛs>?iFã»´_öï?ŠUnknown
pàHost_Send"Nadam/Cast/ReadVariableOp/_1(1=
×£p=ü?9=
×£p=ü?A=
×£p=ü?I=
×£p=ü?aìšÔáÔô<?iÙXOşùï?ŠUnknown
…áHostDataset"/Iterator::Model::ParallelMapV2::Zip[0]::FlatMap(1)\Âõ6@9)\Âõ6@AV-²÷?IV-²÷?aŠÕ$L8?itÂ8Ñıï?ŠUnknown
bâHostIdentity"Identity(1333333ï?9333333ï?A333333ï?I333333ï?aUïÚ\Ğı/?i#>®ÿï?ŠUnknown
fãHost_Send"IteratorGetNext/_5(1ƒÀÊ¡EŞ?9ƒÀÊ¡EŞ?AƒÀÊ¡EŞ?IƒÀÊ¡EŞ?a‡‹û-8
?iÿÿÿÿÿÿï?ŠUnknown2GPU