"ÏÏ
DDeviceIDLE"IDLE1+‡î@ê@A+‡î@ê@QZ©'½£tï?YZ©'½£tï?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_20/dense_60/MatMul(1Ház®‡&@9Ház®‡&@AHáz®‡&@IHáz®‡&@Q-¼ãş*?Y6ÚE¥Svï?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_20/dense_61/MatMul(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@Q?ÓØäı*?YÃZ“ƒxï?ŠUnknown
sDeviceMatMul"sequential_20/dense_60/MatMul(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@Q?ÓØäı*?YPÛàa³yï?ŠUnknown
sDeviceMatMul"sequential_20/dense_61/MatMul(1{®Gáz$@9{®Gáz$@A{®Gáz$@I{®Gáz$@Q"eÄ¸‰(?Y¢!mı;{ï?ŠUnknown
ƒDeviceMatMul"-gradient_tape/sequential_20/dense_61/MatMul_1(1Év¾Ÿo"@9Év¾Ÿo"@AÉv¾Ÿo"@IÉv¾Ÿo"@QóOÆ»)&?YŞ`|ï?ŠUnknown
ƒDeviceMatMul"-gradient_tape/sequential_20/dense_62/MatMul_1(1®Gáz”@9®Gáz”@A®Gáz”@I®Gáz”@Q6[¶Ks?Yºë`úˆ}ï?ŠUnknown
sDeviceMatMul"sequential_20/dense_62/MatMul(1®Gáz”@9®Gáz”@A®Gáz”@I®Gáz”@Q6[¶Ks?Ymù¸”t~ï?ŠUnknown
“	DeviceBiasAddGrad"8gradient_tape/sequential_20/dense_62/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÑV@%`ï?ŠUnknown
‹
DeviceDynamicStitch".gradient_tape/mean_squared_error/DynamicStitch(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q"eÄ¸‰?Yúys$€ï?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_20/dense_62/MatMul(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q"eÄ¸‰?Y#ÌÀè€ï?ŠUnknown
ŸDeviceSquaredDifference">sequential_20/batch_normalization_40/moments/SquaredDifference(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q"eÄ¸‰?YLÀ’­ï?ŠUnknown
…DeviceMean"1sequential_20/batch_normalization_40/moments/mean(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q"eÄ¸‰?YuãX\q‚ï?ŠUnknown
gDevice
LogicalAnd"
LogicalAnd(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QÄ‚'³š¢?Y±|.qƒï?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_1(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QÄ‚'³š¢?Yí†«ƒï?ŠUnknown
qDeviceRealDiv"Nadam/Nadam/update/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?YÛş‘H„ï?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?YÉçœå„ï?ŠUnknown
kDeviceMul"Nadam/Nadam/update_1/mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y·Ğ§‚…ï?ŠUnknown
mDeviceSqrt"Nadam/Nadam/update_4/Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y¥¹²†ï?ŠUnknown
^DevicePow"Nadam/Pow_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y“¢½¼†ï?ŠUnknown
dDeviceDivNoNan"div_no_nan_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y‹!ÈY‡ï?ŠUnknown
‰DeviceTile"5gradient_tape/mean_squared_error/weighted_loss/Tile_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Yot&Óö‡ï?ŠUnknown
™DeviceMul"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_1/Mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y]]+Ş“ˆï?ŠUnknown
‘DeviceSub">gradient_tape/sequential_20/batch_normalization_41/moments/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?YKF0é0‰ï?ŠUnknown
“DeviceBiasAddGrad"8gradient_tape/sequential_20/dense_61/BiasAdd/BiasAddGrad(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y9/5ôÍ‰ï?ŠUnknown
‰DeviceAddV2"4sequential_20/batch_normalization_40/batchnorm/add_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y':ÿjŠï?ŠUnknown
…DeviceMean"1sequential_20/batch_normalization_41/moments/mean(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@Qè°`¡?Y?
‹ï?ŠUnknown
vDeviceAssignAddVariableOp"AssignAddVariableOp(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y`SÜ}‹ï?ŠUnknown
iDeviceSub"Nadam/Nadam/update/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y¿g®ó‹ï?ŠUnknown
mDeviceAddV2"Nadam/Nadam/update_1/add(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y|€iŒï?ŠUnknown
qDeviceSquare"Nadam/Nadam/update_2/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y}RßŒï?ŠUnknown
u DeviceRealDiv"Nadam/Nadam/update_2/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?YÜ¤$Uï?ŠUnknown
m!DeviceMul"Nadam/Nadam/update_3/mul_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y;¹öÊï?ŠUnknown
m"DeviceMul"Nadam/Nadam/update_3/mul_6(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?YšÍÈ@ï?ŠUnknown
k#DeviceSub"Nadam/Nadam/update_3/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Yùáš¶ï?ŠUnknown
u$DeviceRealDiv"Nadam/Nadam/update_4/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?YXöl,ï?ŠUnknown
m%DeviceMul"Nadam/Nadam/update_6/mul_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y·
?¢ï?ŠUnknown
k&DeviceSub"Nadam/Nadam/update_6/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y ï?ŠUnknown
u'DeviceRealDiv"Nadam/Nadam/update_6/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y!u3ãï?ŠUnknown
u(DeviceRealDiv"Nadam/Nadam/update_8/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y"ÔGµ‘ï?ŠUnknown
m)DeviceMul"Nadam/Nadam/update_9/mul_4(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y#3\‡y‘ï?ŠUnknown
\*DeviceSub"	Nadam/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y$’pYï‘ï?ŠUnknown
^+DeviceSub"Nadam/sub_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y%ñ„+e’ï?ŠUnknown
Ÿ,Device	RsqrtGrad"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/RsqrtGrad(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y&P™ıÚ’ï?ŠUnknown
—-DeviceNeg"Dgradient_tape/sequential_20/batch_normalization_41/batchnorm/sub/Neg(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y'¯­ÏP“ï?ŠUnknown
….DeviceSquaredDifference"$mean_squared_error/SquaredDifference(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y(Â¡Æ“ï?ŠUnknown
‹/DeviceSub"8sequential_20/batch_normalization_40/AssignMovingAvg/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y)mÖs<”ï?ŠUnknown
‡0DeviceMul"4sequential_20/batch_normalization_40/batchnorm/mul_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y*ÌêE²”ï?ŠUnknown
…1DeviceSub"2sequential_20/batch_normalization_41/batchnorm/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y++ÿ(•ï?ŠUnknown
u2DeviceBiasAdd"sequential_20/dense_60/BiasAdd(1/İ$•@9/İ$•@A/İ$•@I/İ$•@Q-À…t?Y,Šê•ï?ŠUnknown
x3DeviceAssignAddVariableOp"AssignAddVariableOp_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YŞ8W²–ï?ŠUnknown
x4DeviceAssignAddVariableOp"AssignAddVariableOp_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yçšz‰–ï?ŠUnknown
x5DeviceAssignAddVariableOp"AssignAddVariableOp_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YB–ŞBÿ–ï?ŠUnknown
X6DeviceCast"Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YôD"u—ï?ŠUnknown
`7DeviceCast"Nadam/Cast_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¦óeÓê—ï?ŠUnknown
`8DeviceCast"Nadam/Cast_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YX¢©›`˜ï?ŠUnknown
‚9DeviceAssignAddVariableOp"Nadam/Nadam/AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y
QícÖ˜ï?ŠUnknown
k:DeviceSqrt"Nadam/Nadam/update/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¼ÿ0,L™ï?ŠUnknown
o;DeviceSquare"Nadam/Nadam/update/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yn®tôÁ™ï?ŠUnknown
k<DeviceAddV2"Nadam/Nadam/update/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y ]¸¼7šï?ŠUnknown
m=DeviceAddV2"Nadam/Nadam/update/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÒü„­šï?ŠUnknown
k>DeviceMul"Nadam/Nadam/update/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y„º?M#›ï?ŠUnknown
s?DeviceRealDiv"Nadam/Nadam/update/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y6iƒ™›ï?ŠUnknown
m@DeviceMul"Nadam/Nadam/update_1/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YèÇİœï?ŠUnknown
mADeviceMul"Nadam/Nadam/update_1/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YšÆ
¦„œï?ŠUnknown
sBDeviceRealDiv"Nadam/Nadam/update_1/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YLuNnúœï?ŠUnknown
uCDeviceRealDiv"Nadam/Nadam/update_1/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yş#’6pï?ŠUnknown
uDDeviceRealDiv"Nadam/Nadam/update_1/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y°ÒÕşåï?ŠUnknown
mEDeviceSqrt"Nadam/Nadam/update_2/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YbÇ[ï?ŠUnknown
oFDeviceAddV2"Nadam/Nadam/update_2/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y0]Ñï?ŠUnknown
oGDeviceAddV2"Nadam/Nadam/update_2/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÆŞ WGŸï?ŠUnknown
mHDeviceMul"Nadam/Nadam/update_2/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yxä½Ÿï?ŠUnknown
sIDeviceRealDiv"Nadam/Nadam/update_2/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y*<(è2 ï?ŠUnknown
uJDeviceRealDiv"Nadam/Nadam/update_2/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÜêk°¨ ï?ŠUnknown
mKDeviceSqrt"Nadam/Nadam/update_3/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y™¯x¡ï?ŠUnknown
oLDeviceAddV2"Nadam/Nadam/update_3/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y@Hó@”¡ï?ŠUnknown
sMDeviceRealDiv"Nadam/Nadam/update_3/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yòö6	
¢ï?ŠUnknown
uNDeviceRealDiv"Nadam/Nadam/update_3/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¤¥zÑ¢ï?ŠUnknown
uODeviceRealDiv"Nadam/Nadam/update_3/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YVT¾™õ¢ï?ŠUnknown
qPDeviceSquare"Nadam/Nadam/update_4/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Ybk£ï?ŠUnknown
mQDeviceAddV2"Nadam/Nadam/update_4/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yº±E*á£ï?ŠUnknown
oRDeviceAddV2"Nadam/Nadam/update_4/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yl`‰òV¤ï?ŠUnknown
oSDeviceAddV2"Nadam/Nadam/update_4/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÍºÌ¤ï?ŠUnknown
kTDeviceMul"Nadam/Nadam/update_4/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YĞ½ƒB¥ï?ŠUnknown
mUDeviceMul"Nadam/Nadam/update_4/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y‚lTK¸¥ï?ŠUnknown
mVDeviceMul"Nadam/Nadam/update_4/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y4˜.¦ï?ŠUnknown
mWDeviceMul"Nadam/Nadam/update_4/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YæÉÛÛ£¦ï?ŠUnknown
kXDeviceSub"Nadam/Nadam/update_4/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y˜x¤§ï?ŠUnknown
sYDeviceRealDiv"Nadam/Nadam/update_4/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YJ'cl§ï?ŠUnknown
uZDeviceRealDiv"Nadam/Nadam/update_4/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YüÕ¦4¨ï?ŠUnknown
u[DeviceRealDiv"Nadam/Nadam/update_4/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y®„êüz¨ï?ŠUnknown
m\DeviceSqrt"Nadam/Nadam/update_5/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y`3.Åğ¨ï?ŠUnknown
o]DeviceAddV2"Nadam/Nadam/update_5/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yâqf©ï?ŠUnknown
k^DeviceMul"Nadam/Nadam/update_5/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÄµUÜ©ï?ŠUnknown
m_DeviceMul"Nadam/Nadam/update_5/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yv?ùRªï?ŠUnknown
m`DeviceMul"Nadam/Nadam/update_5/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y(î<æÇªï?ŠUnknown
maDeviceMul"Nadam/Nadam/update_5/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÚœ€®=«ï?ŠUnknown
sbDeviceRealDiv"Nadam/Nadam/update_5/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YŒKÄv³«ï?ŠUnknown
ucDeviceRealDiv"Nadam/Nadam/update_5/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y>ú?)¬ï?ŠUnknown
udDeviceRealDiv"Nadam/Nadam/update_5/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yğ¨KŸ¬ï?ŠUnknown
ueDeviceRealDiv"Nadam/Nadam/update_5/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¢WÏ­ï?ŠUnknown
mfDeviceSqrt"Nadam/Nadam/update_6/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YTÓ—Š­ï?ŠUnknown
ogDeviceAddV2"Nadam/Nadam/update_6/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yµ` ®ï?ŠUnknown
ohDeviceAddV2"Nadam/Nadam/update_6/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¸cZ(v®ï?ŠUnknown
kiDeviceMul"Nadam/Nadam/update_6/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yjğë®ï?ŠUnknown
mjDeviceMul"Nadam/Nadam/update_6/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÁá¸a¯ï?ŠUnknown
skDeviceRealDiv"Nadam/Nadam/update_6/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÎo%×¯ï?ŠUnknown
ulDeviceRealDiv"Nadam/Nadam/update_6/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y€iIM°ï?ŠUnknown
mmDeviceSqrt"Nadam/Nadam/update_7/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y2Í¬Ã°ï?ŠUnknown
qnDeviceSquare"Nadam/Nadam/update_7/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yä{ğÙ8±ï?ŠUnknown
ooDeviceAddV2"Nadam/Nadam/update_7/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y–*4¢®±ï?ŠUnknown
kpDeviceMul"Nadam/Nadam/update_7/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YHÙwj$²ï?ŠUnknown
mqDeviceMul"Nadam/Nadam/update_7/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yú‡»2š²ï?ŠUnknown
mrDeviceMul"Nadam/Nadam/update_7/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¬6ÿú³ï?ŠUnknown
msDeviceMul"Nadam/Nadam/update_7/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y^åBÃ…³ï?ŠUnknown
ktDeviceSub"Nadam/Nadam/update_7/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y”†‹û³ï?ŠUnknown
uuDeviceRealDiv"Nadam/Nadam/update_7/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÂBÊSq´ï?ŠUnknown
uvDeviceRealDiv"Nadam/Nadam/update_7/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Ytñç´ï?ŠUnknown
owDeviceAddV2"Nadam/Nadam/update_8/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y& Qä\µï?ŠUnknown
mxDeviceMul"Nadam/Nadam/update_8/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YØN•¬Òµï?ŠUnknown
syDeviceRealDiv"Nadam/Nadam/update_8/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YŠıØtH¶ï?ŠUnknown
uzDeviceRealDiv"Nadam/Nadam/update_8/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y<¬=¾¶ï?ŠUnknown
m{DeviceSqrt"Nadam/Nadam/update_9/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YîZ`4·ï?ŠUnknown
q|DeviceSquare"Nadam/Nadam/update_9/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y 	¤Í©·ï?ŠUnknown
m}DeviceAddV2"Nadam/Nadam/update_9/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YR¸ç•¸ï?ŠUnknown
m~DeviceMul"Nadam/Nadam/update_9/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yg+^•¸ï?ŠUnknown
mDeviceMul"Nadam/Nadam/update_9/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¶o&¹ï?ŠUnknown
v€DeviceRealDiv"Nadam/Nadam/update_9/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YhÄ²î€¹ï?ŠUnknown
vDeviceRealDiv"Nadam/Nadam/update_9/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Ysö¶ö¹ï?ŠUnknown
]‚DevicePow"	Nadam/Pow(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÌ!:lºï?ŠUnknown
_ƒDeviceAddV2"	Nadam/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y~Ğ}Gâºï?ŠUnknown
a„DeviceAddV2"Nadam/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y0ÁX»ï?ŠUnknown
i…DeviceAddN"Nadam/gradients/AddN(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yâ-ØÍ»ï?ŠUnknown
k†DeviceAddN"Nadam/gradients/AddN_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y”ÜH C¼ï?ŠUnknown
k‡DeviceAddN"Nadam/gradients/AddN_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YF‹Œh¹¼ï?ŠUnknown
kˆDeviceAddN"Nadam/gradients/AddN_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yø9Ğ0/½ï?ŠUnknown
_‰DeviceMul"Nadam/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yªèù¤½ï?ŠUnknown
_ŠDeviceMul"Nadam/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y\—WÁ¾ï?ŠUnknown
_‹DeviceSub"Nadam/sub_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YF›‰¾ï?ŠUnknown
_ŒDeviceSub"Nadam/sub_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÀôŞQ¿ï?ŠUnknown
YDeviceSqrt"Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yr£"|¿ï?ŠUnknown
YDeviceSum"Sum_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y$Rfâñ¿ï?ŠUnknown
zDeviceCast"%gradient_tape/mean_squared_error/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÖ ªªgÀï?ŠUnknown
€DeviceRealDiv"(gradient_tape/mean_squared_error/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yˆ¯írİÀï?ŠUnknown
˜‘DeviceDivNoNan"?gradient_tape/mean_squared_error/weighted_loss/value/div_no_nan(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y:^1;SÁï?ŠUnknown
œ’DeviceSum"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/add_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YìuÉÁï?ŠUnknown
š“DeviceMul"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_1/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y»¸Ë>Âï?ŠUnknown
œ”DeviceSum"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YPjü“´Âï?ŠUnknown
˜•DeviceNeg"Dgradient_tape/sequential_20/batch_normalization_40/batchnorm/sub/Neg(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y@\*Ãï?ŠUnknown
¢–DeviceBroadcastTo"Fgradient_tape/sequential_20/batch_normalization_40/moments/BroadcastTo(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y´Çƒ$ Ãï?ŠUnknown
¤—DeviceBroadcastTo"Hgradient_tape/sequential_20/batch_normalization_40/moments/BroadcastTo_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YfvÇìÄï?ŠUnknown
’˜DeviceSub">gradient_tape/sequential_20/batch_normalization_40/moments/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y%µ‹Äï?ŠUnknown
š™DeviceRealDiv"Bgradient_tape/sequential_20/batch_normalization_40/moments/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÊÓN}Åï?ŠUnknown
œšDeviceRealDiv"Dgradient_tape/sequential_20/batch_normalization_40/moments/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y|‚’EwÅï?ŠUnknown
œ›DeviceSum"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/add_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y.1ÖíÅï?ŠUnknown
˜œDeviceMul"Dgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YàßÖbÆï?ŠUnknown
šDeviceMul"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y’]ØÆï?ŠUnknown
œDeviceMul"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_1/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YD=¡fNÇï?ŠUnknown
œŸDeviceSum"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yöëä.ÄÇï?ŠUnknown
¢ DeviceBroadcastTo"Fgradient_tape/sequential_20/batch_normalization_41/moments/BroadcastTo(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¨š(÷9Èï?ŠUnknown
¤¡DeviceBroadcastTo"Hgradient_tape/sequential_20/batch_normalization_41/moments/BroadcastTo_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YZIl¿¯Èï?ŠUnknown
œ¢DeviceRealDiv"Dgradient_tape/sequential_20/batch_normalization_41/moments/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yø¯‡%Éï?ŠUnknown
”£DeviceBiasAddGrad"8gradient_tape/sequential_20/dense_60/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¾¦óO›Éï?ŠUnknown
„¤DeviceEluGrad",gradient_tape/sequential_20/dense_60/EluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YpU7Êï?ŠUnknown
„¥DeviceEluGrad",gradient_tape/sequential_20/dense_61/EluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y"{à†Êï?ŠUnknown
‡¦DeviceCast"2mean_squared_error/weighted_loss/num_elements/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÔ²¾¨üÊï?ŠUnknown
§DeviceDivNoNan"&mean_squared_error/weighted_loss/value(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y†aqrËï?ŠUnknown
¬¨DeviceAssignSubVariableOp"Hsequential_20/batch_normalization_40/AssignMovingAvg/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y8F9èËï?ŠUnknown
©DeviceSub":sequential_20/batch_normalization_40/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yê¾‰^Ìï?ŠUnknown
ŠªDeviceRsqrt"4sequential_20/batch_normalization_40/batchnorm/Rsqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YœmÍÉÓÌï?ŠUnknown
ˆ«DeviceMul"4sequential_20/batch_normalization_40/batchnorm/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YN’IÍï?ŠUnknown
Š¬DeviceMean"5sequential_20/batch_normalization_40/moments/variance(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y ËTZ¿Íï?ŠUnknown
Œ­DeviceMul"8sequential_20/batch_normalization_41/AssignMovingAvg/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y²y˜"5Îï?ŠUnknown
Œ®DeviceSub"8sequential_20/batch_normalization_41/AssignMovingAvg/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yd(ÜêªÎï?ŠUnknown
®¯DeviceAssignSubVariableOp"Jsequential_20/batch_normalization_41/AssignMovingAvg_1/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y×³ Ïï?ŠUnknown
°DeviceSub":sequential_20/batch_normalization_41/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YÈ…c{–Ïï?ŠUnknown
ˆ±DeviceAddV2"2sequential_20/batch_normalization_41/batchnorm/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yz4§CĞï?ŠUnknown
Š²DeviceAddV2"4sequential_20/batch_normalization_41/batchnorm/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y,ãê‚Ğï?ŠUnknown
†³DeviceMul"2sequential_20/batch_normalization_41/batchnorm/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YŞ‘.Ô÷Ğï?ŠUnknown
ˆ´DeviceMul"4sequential_20/batch_normalization_41/batchnorm/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y@rœmÑï?ŠUnknown
 µDeviceSquaredDifference">sequential_20/batch_normalization_41/moments/SquaredDifference(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YBïµdãÑï?ŠUnknown
Š¶DeviceMean"5sequential_20/batch_normalization_41/moments/variance(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Yôù,YÒï?ŠUnknown
n·DeviceElu"sequential_20/dense_60/Elu(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?Y¦L=õÎÒï?ŠUnknown
n¸DeviceElu"sequential_20/dense_61/Elu(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q\‰¬ër?YXû€½DÓï?ŠUnknown
W¹DeviceMul"Mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y ÔL“Óï?ŠUnknown
nºDeviceSqrt"Nadam/Nadam/update_1/Sqrt(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?YâD'ÜáÓï?ŠUnknown
p»DeviceAddV2"Nadam/Nadam/update_1/add_3(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y§izk0Ôï?ŠUnknown
l¼DeviceMul"Nadam/Nadam/update_2/mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?YlÍú~Ôï?ŠUnknown
n½DeviceMul"Nadam/Nadam/update_3/mul_4(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y1³ ŠÍÔï?ŠUnknown
n¾DeviceAddV2"Nadam/Nadam/update_7/add(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Yö×sÕï?ŠUnknown
n¿DeviceSqrt"Nadam/Nadam/update_8/Sqrt(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y»üÆ¨jÕï?ŠUnknown
nÀDeviceMul"Nadam/Nadam/update_8/mul_4(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y€!8¹Õï?ŠUnknown
pÁDeviceAddV2"Nadam/Nadam/update_9/add_2(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?YEFmÇÖï?ŠUnknown
lÂDeviceMul"Nadam/Nadam/update_9/mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y
kÀVVÖï?ŠUnknown
nÃDeviceMul"Nadam/Nadam/update_9/mul_2(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?YÏæ¤Öï?ŠUnknown
lÄDeviceSub"Nadam/Nadam/update_9/sub(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Y”´fuóÖï?ŠUnknown
_ÅDeviceMul"Nadam/mul_6(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?YYÙ¹B×ï?ŠUnknown
xÆDeviceSub"$gradient_tape/mean_squared_error/sub(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Yş”×ï?ŠUnknown
ŠÇDeviceRsqrt"4sequential_20/batch_normalization_41/batchnorm/Rsqrt(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QT1ÉÔ£?Yã"`#ß×ï?ŠUnknown
yÈDeviceAssignAddVariableOp"AssignAddVariableOp_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YZ—â¨-Øï?ŠUnknown
[ÉDeviceCast"Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÑe.|Øï?ŠUnknown
hÊDevice_Send"IteratorGetNext/_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YH€ç³ÊØï?ŠUnknown
nËDeviceAddV2"Nadam/Nadam/update/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y¿ôi9Ùï?ŠUnknown
nÌDeviceAddV2"Nadam/Nadam/update/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y6iì¾gÙï?ŠUnknown
jÍDeviceMul"Nadam/Nadam/update/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y­İnD¶Ùï?ŠUnknown
lÎDeviceMul"Nadam/Nadam/update/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y$RñÉÚï?ŠUnknown
lÏDeviceMul"Nadam/Nadam/update/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y›ÆsOSÚï?ŠUnknown
lĞDeviceMul"Nadam/Nadam/update/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y;öÔ¡Úï?ŠUnknown
lÑDeviceMul"Nadam/Nadam/update/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y‰¯xZğÚï?ŠUnknown
lÒDeviceMul"Nadam/Nadam/update/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y $ûß>Ûï?ŠUnknown
rÓDeviceSquare"Nadam/Nadam/update_1/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yw˜}eÛï?ŠUnknown
pÔDeviceAddV2"Nadam/Nadam/update_1/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yî ëÛÛï?ŠUnknown
pÕDeviceAddV2"Nadam/Nadam/update_1/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Ye‚p*Üï?ŠUnknown
nÖDeviceMul"Nadam/Nadam/update_1/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÜõöxÜï?ŠUnknown
n×DeviceMul"Nadam/Nadam/update_1/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YSj‡{ÇÜï?ŠUnknown
nØDeviceMul"Nadam/Nadam/update_1/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÊŞ	İï?ŠUnknown
nÙDeviceMul"Nadam/Nadam/update_1/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YASŒ†dİï?ŠUnknown
lÚDeviceSub"Nadam/Nadam/update_1/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y¸Ç³İï?ŠUnknown
vÛDeviceRealDiv"Nadam/Nadam/update_1/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y/<‘‘Şï?ŠUnknown
nÜDeviceAddV2"Nadam/Nadam/update_2/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y¦°PŞï?ŠUnknown
pİDeviceAddV2"Nadam/Nadam/update_2/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y%–œŞï?ŠUnknown
nŞDeviceMul"Nadam/Nadam/update_2/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y”™"íŞï?ŠUnknown
nßDeviceMul"Nadam/Nadam/update_2/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y›§;ßï?ŠUnknown
nàDeviceMul"Nadam/Nadam/update_2/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y‚‚-Šßï?ŠUnknown
náDeviceMul"Nadam/Nadam/update_2/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YùöŸ²Øßï?ŠUnknown
nâDeviceMul"Nadam/Nadam/update_2/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Ypk"8'àï?ŠUnknown
lãDeviceSub"Nadam/Nadam/update_2/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yçß¤½uàï?ŠUnknown
väDeviceRealDiv"Nadam/Nadam/update_2/truediv_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y^T'CÄàï?ŠUnknown
råDeviceSquare"Nadam/Nadam/update_3/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÕÈ©Èáï?ŠUnknown
næDeviceAddV2"Nadam/Nadam/update_3/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YL=,Naáï?ŠUnknown
pçDeviceAddV2"Nadam/Nadam/update_3/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÃ±®Ó¯áï?ŠUnknown
pèDeviceAddV2"Nadam/Nadam/update_3/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y:&1Yşáï?ŠUnknown
léDeviceMul"Nadam/Nadam/update_3/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y±š³ŞLâï?ŠUnknown
nêDeviceMul"Nadam/Nadam/update_3/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y(6d›âï?ŠUnknown
nëDeviceMul"Nadam/Nadam/update_3/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YŸƒ¸ééâï?ŠUnknown
nìDeviceMul"Nadam/Nadam/update_3/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yø:o8ãï?ŠUnknown
víDeviceRealDiv"Nadam/Nadam/update_3/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yl½ô†ãï?ŠUnknown
pîDeviceAddV2"Nadam/Nadam/update_4/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yá?zÕãï?ŠUnknown
nïDeviceMul"Nadam/Nadam/update_4/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y{UÂÿ#äï?ŠUnknown
nğDeviceMul"Nadam/Nadam/update_4/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YòÉD…räï?ŠUnknown
nñDeviceMul"Nadam/Nadam/update_4/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yi>Ç
Áäï?ŠUnknown
ròDeviceSquare"Nadam/Nadam/update_5/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yà²Iåï?ŠUnknown
nóDeviceAddV2"Nadam/Nadam/update_5/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YW'Ì^åï?ŠUnknown
pôDeviceAddV2"Nadam/Nadam/update_5/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÎ›N›¬åï?ŠUnknown
põDeviceAddV2"Nadam/Nadam/update_5/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YEÑ ûåï?ŠUnknown
nöDeviceMul"Nadam/Nadam/update_5/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y¼„S¦Iæï?ŠUnknown
n÷DeviceMul"Nadam/Nadam/update_5/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y3ùÕ+˜æï?ŠUnknown
nøDeviceMul"Nadam/Nadam/update_5/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YªmX±ææï?ŠUnknown
lùDeviceSub"Nadam/Nadam/update_5/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y!âÚ65çï?ŠUnknown
rúDeviceSquare"Nadam/Nadam/update_6/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y˜V]¼ƒçï?ŠUnknown
nûDeviceAddV2"Nadam/Nadam/update_6/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YËßAÒçï?ŠUnknown
püDeviceAddV2"Nadam/Nadam/update_6/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y†?bÇ èï?ŠUnknown
nıDeviceMul"Nadam/Nadam/update_6/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yı³äLoèï?ŠUnknown
nşDeviceMul"Nadam/Nadam/update_6/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yt(gÒ½èï?ŠUnknown
nÿDeviceMul"Nadam/Nadam/update_6/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YëœéWéï?ŠUnknown
n€DeviceMul"Nadam/Nadam/update_6/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YblİZéï?ŠUnknown
vDeviceRealDiv"Nadam/Nadam/update_6/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÙ…îb©éï?ŠUnknown
p‚DeviceAddV2"Nadam/Nadam/update_7/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YPúpè÷éï?ŠUnknown
pƒDeviceAddV2"Nadam/Nadam/update_7/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÇnómFêï?ŠUnknown
n„DeviceMul"Nadam/Nadam/update_7/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y>ãuó”êï?ŠUnknown
n…DeviceMul"Nadam/Nadam/update_7/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YµWøxãêï?ŠUnknown
n†DeviceMul"Nadam/Nadam/update_7/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y,Ìzş1ëï?ŠUnknown
t‡DeviceRealDiv"Nadam/Nadam/update_7/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y£@ıƒ€ëï?ŠUnknown
vˆDeviceRealDiv"Nadam/Nadam/update_7/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yµ	Ïëï?ŠUnknown
r‰DeviceSquare"Nadam/Nadam/update_8/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y‘)ìï?ŠUnknown
nŠDeviceAddV2"Nadam/Nadam/update_8/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y„lìï?ŠUnknown
p‹DeviceAddV2"Nadam/Nadam/update_8/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yšºìï?ŠUnknown
pŒDeviceAddV2"Nadam/Nadam/update_8/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yö†‰	íï?ŠUnknown
lDeviceMul"Nadam/Nadam/update_8/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Ymû¥Wíï?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yäo*¦íï?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y[ä°ôíï?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÒX“5Cîï?ŠUnknown
n‘DeviceMul"Nadam/Nadam/update_8/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YIÍ»‘îï?ŠUnknown
l’DeviceSub"Nadam/Nadam/update_8/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÀA˜@àîï?ŠUnknown
v“DeviceRealDiv"Nadam/Nadam/update_8/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y7¶Æ.ïï?ŠUnknown
p”DeviceAddV2"Nadam/Nadam/update_9/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y®*K}ïï?ŠUnknown
p•DeviceAddV2"Nadam/Nadam/update_9/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y%ŸÑËïï?ŠUnknown
n–DeviceMul"Nadam/Nadam/update_9/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yœ¢Vğï?ŠUnknown
n—DeviceMul"Nadam/Nadam/update_9/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yˆ$Ühğï?ŠUnknown
t˜DeviceRealDiv"Nadam/Nadam/update_9/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YŠü¦a·ğï?ŠUnknown
v™DeviceRealDiv"Nadam/Nadam/update_9/truediv_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yq)çñï?ŠUnknown
_šDevicePow"Nadam/Pow_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yxå«lTñï?ŠUnknown
]›DeviceMul"	Nadam/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YïY.ò¢ñï?ŠUnknown
_œDeviceMul"Nadam/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YfÎ°wññï?ŠUnknown
_DeviceMul"Nadam/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YİB3ı?òï?ŠUnknown
_DeviceMul"Nadam/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YT·µ‚òï?ŠUnknown
_ŸDeviceMul"Nadam/mul_7(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YË+8İòï?ŠUnknown
_ DeviceSub"Nadam/sub_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YB º+óï?ŠUnknown
_¡DeviceSub"Nadam/sub_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y¹=zóï?ŠUnknown
_¢DeviceSub"Nadam/sub_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y0‰¿˜Èóï?ŠUnknown
_£DeviceSub"Nadam/sub_7(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y§ıAôï?ŠUnknown
c¤DeviceDivNoNan"
div_no_nan(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YrÄ£eôï?ŠUnknown
¥Device_Recv")gradient_tape/mean_squared_error/Fill/_20(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y•æF)´ôï?ŠUnknown
x¦DeviceMul"$gradient_tape/mean_squared_error/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y[É®õï?ŠUnknown
z§DeviceMul"&gradient_tape/mean_squared_error/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YƒÏK4Qõï?ŠUnknown
˜¨DeviceMul"Dgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YúCÎ¹Ÿõï?ŠUnknown
š©DeviceMul"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yq¸P?îõï?ŠUnknown
œªDeviceMul"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_1/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yè,ÓÄ<öï?ŠUnknown
š«DeviceMul"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y_¡UJ‹öï?ŠUnknown
œ¬DeviceMul"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_2/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÖØÏÙöï?ŠUnknown
”­DeviceCast"?gradient_tape/sequential_20/batch_normalization_40/moments/Cast(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YMŠZU(÷ï?ŠUnknown
–®DeviceCast"Agradient_tape/sequential_20/batch_normalization_40/moments/Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÄşÜÚv÷ï?ŠUnknown
’¯DeviceMul">gradient_tape/sequential_20/batch_normalization_40/moments/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y;s_`Å÷ï?ŠUnknown
°Device_Recv"Hgradient_tape/sequential_20/batch_normalization_40/moments/floordiv_1/_8(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y²çáåøï?ŠUnknown
”±DeviceMul"@gradient_tape/sequential_20/batch_normalization_40/moments/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y)\dkbøï?ŠUnknown
 ²Device	RsqrtGrad"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/RsqrtGrad(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y Ğæğ°øï?ŠUnknown
š³DeviceMul"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YEivÿøï?ŠUnknown
œ´DeviceMul"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_2/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y¹ëûMùï?ŠUnknown
”µDeviceCast"?gradient_tape/sequential_20/batch_normalization_41/moments/Cast(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y.nœùï?ŠUnknown
–¶DeviceCast"Agradient_tape/sequential_20/batch_normalization_41/moments/Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y|¢ğëùï?ŠUnknown
’·DeviceMul">gradient_tape/sequential_20/batch_normalization_41/moments/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YósŒ9úï?ŠUnknown
”¸DeviceMul"@gradient_tape/sequential_20/batch_normalization_41/moments/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yj‹õˆúï?ŠUnknown
š¹DeviceRealDiv"Bgradient_tape/sequential_20/batch_normalization_41/moments/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yáÿw—Öúï?ŠUnknown
xºDeviceSum"$mean_squared_error/weighted_loss/Sum(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YXtú%ûï?ŠUnknown
Œ»DeviceMul"8sequential_20/batch_normalization_40/AssignMovingAvg/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YÏè|¢sûï?ŠUnknown
®¼DeviceAssignSubVariableOp"Jsequential_20/batch_normalization_40/AssignMovingAvg_1/AssignSubVariableOp(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YF]ÿ'Âûï?ŠUnknown
½DeviceMul":sequential_20/batch_normalization_40/AssignMovingAvg_1/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y½Ñ­üï?ŠUnknown
ˆ¾DeviceAddV2"2sequential_20/batch_normalization_40/batchnorm/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y4F3_üï?ŠUnknown
†¿DeviceMul"2sequential_20/batch_normalization_40/batchnorm/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y«º†¸­üï?ŠUnknown
†ÀDeviceSub"2sequential_20/batch_normalization_40/batchnorm/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y"/	>üüï?ŠUnknown
¬ÁDeviceAssignSubVariableOp"Hsequential_20/batch_normalization_41/AssignMovingAvg/AssignSubVariableOp(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y™£‹ÃJıï?ŠUnknown
ÂDeviceMul":sequential_20/batch_normalization_41/AssignMovingAvg_1/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?YI™ıï?ŠUnknown
ˆÃDeviceMul"4sequential_20/batch_normalization_41/batchnorm/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Y‡ŒÎçıï?ŠUnknown
vÄDeviceBiasAdd"sequential_20/dense_61/BiasAdd(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yş T6şï?ŠUnknown
vÅDeviceBiasAdd"sequential_20/dense_62/BiasAdd(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @Qè°`¡?Yuu•Ù„şï?ŠUnknown
ŒÆDevice	_HostRecv"2gradient_tape/mean_squared_error/DynamicStitch/_26(1‰A`åĞ"û?9‰A`åĞ"û?A‰A`åĞ"û?I‰A`åĞ"û?Q€–¤A ?Yç}%àÅşï?ŠUnknown
ÇDevice_Recv"+gradient_tape/mean_squared_error/Prod_1/_22(1ffffffğ?9ffffffğ?Affffffğ?Iffffffğ?QTøDõH¦ó>Yqh·,íşï?ŠUnknown
hÈDevice_Send"IteratorGetNext/_3(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>Y¬¢xoÿï?ŠUnknown
^ÉDevice_Recv"Size/_16(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>YçÜ9²;ÿï?ŠUnknown
€ÊDevice_Recv"*gradient_tape/mean_squared_error/Shape/_18(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>Y"ûôbÿï?ŠUnknown
ƒËDevice_Recv"-gradient_tape/mean_squared_error/floordiv/_24(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>Y]Q¼7Šÿï?ŠUnknown
ÌDevice_Recv"Ggradient_tape/sequential_20/batch_normalization_40/moments/floordiv/_10(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>Y˜‹}z±ÿï?ŠUnknown
ŸÍDevice_Recv"Igradient_tape/sequential_20/batch_normalization_41/moments/floordiv_1/_12(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>YÓÅ>½Øÿï?ŠUnknown
fÎDevice_Recv"strided_slice/_6(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?Qè°`¡ó>Y     ğ?ŠUnknown
pÏDevice_Recv"Ggradient_tape/sequential_20/batch_normalization_41/moments/floordiv/_14(Y     ğ?ŠUnknown
CĞHostIDLE"IDLE1q=
×C;Ã@Aq=
×C;Ã@a¥aë?i¥aë?ŠUnknown
vÑHostFlushSummaryWriter"FlushSummaryWriter(1{®Gáã“@9{®Gáã“@A{®Gáã“@I{®Gáã“@a1KÏØáí»?iK0QÚ~î?ŠUnknown
fÒHost_Send"IteratorGetNext/_3(1²ï§Æÿe@9²ï§Æÿe@A²ï§Æÿe@I²ï§Æÿe@a.Böbıã?i$¼Fjúî?ŠUnknown
fÓHost_Send"IteratorGetNext/_1(1Zd;ßOÅa@9Zd;ßOÅa@AZd;ßOÅa@IZd;ßOÅa@aAŸÈÎôˆ?i‘F÷]:^ï?ŠUnknown
fÔHost
LogicalAnd"
LogicalAnd(1^ºI«P@9^ºI«P@A^ºI«P@I^ºI«P@a%¼Vrgw?i	ôÛš	ï?ŠUnknown
jÕHostWriteSummary"WriteSummary(1V-²oL@9V-²oL@AV-²oL@IV-²oL@aÏÇ1áëös?i™Wr÷´ï?ŠUnknown
‹ÖHostDataset"5Iterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat(1Év¾Ÿo8@9Év¾Ÿo8@AÙÎ÷Sƒ4@IÙÎ÷Sƒ4@a^e\ÆÍ\?iHŠÌU^Ãï?ŠUnknown
e×HostDataset"Iterator::Model(1¸…ëQ˜?@9¸…ëQ˜?@Aü©ñÒMB0@Iü©ñÒMB0@axÒf«˜ÔV?i±="¢ÈÎï?ŠUnknown
tØHostDataset"Iterator::Model::ParallelMapV2(1yé&1¬.@9yé&1¬.@Ayé&1¬.@Iyé&1¬.@aÂÈöšÎˆU?i¹o	Ùï?ŠUnknown
_ÙHostGatherV2"GatherV2(1ö(\Âu(@9ö(\Âu(@Aö(\Âu(@Iö(\Âu(@a)T[L,Q?i*c/#âï?ŠUnknown
•ÚHostDataset"?Iterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate(1î|?5^º2@9î|?5^º2@Ah‘í|?µ$@Ih‘í|?µ$@aRUºßM?i¿Ñ^'héï?ŠUnknown
¥ÛHostDataset"OIterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate[0]::TensorSlice(1sh‘í|¿ @9sh‘í|¿ @Ash‘í|¿ @Ish‘í|¿ @aµ.é[`„G?iÌu?Iïï?ŠUnknown
aÜHostGatherV2"
GatherV2_1(1øSã¥›D@9øSã¥›D@AøSã¥›D@IøSã¥›D@aëª†½A?iÆ¶ö ¸óï?ŠUnknown
mİHostIteratorGetNext"IteratorGetNext(1Tã¥›Ä @9Tã¥›Ä @ATã¥›Ä @ITã¥›Ä @aºÆ¡÷P??iÿªëš÷ï?ŠUnknown
yŞHostDataset"#Iterator::Model::ParallelMapV2::Zip(1ºI+I@9ºI+I@AF¶óıÔø@IF¶óıÔø@a^ÏPUÅr=?iUÀCIûï?ŠUnknown
—ßHostDataset"AIterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat::FromTensor(1‘í|?5^@9‘í|?5^ÿ?A‘í|?5^@I‘í|?5^ÿ?a;šìæ6?i`è 
şï?ŠUnknown
…àHostDataset"/Iterator::Model::ParallelMapV2::Zip[0]::FlatMap(1/İ$a4@9/İ$a4@AÑ"Ûù~jú?IÑ"Ûù~jú?a„áX¼Û‹"?iî­Y¾2ÿï?ŠUnknown
báHostIdentity"Identity(1ƒÀÊ¡Eò?9ƒÀÊ¡Eò?AƒÀÊ¡Eò?IƒÀÊ¡Eò?a5BÊ4¨?i      ğ?ŠUnknown*ÃÎ
DeviceMatMul"+gradient_tape/sequential_20/dense_60/MatMul(1Ház®‡&@9Ház®‡&@AHáz®‡&@IHáz®‡&@QÏP9	-Ëˆ?YÏP9	-Ëˆ?ŠUnknown
DeviceMatMul"+gradient_tape/sequential_20/dense_61/MatMul(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@Qc‚zËœÊˆ?Y™éYêäÊ˜?ŠUnknown
sDeviceMatMul"sequential_20/dense_60/MatMul(1ºI+‡&@9ºI+‡&@AºI+‡&@IºI+‡&@Qc‚zËœÊˆ?Ye•¨˜¢?ŠUnknown
sDeviceMatMul"sequential_20/dense_61/MatMul(1{®Gáz$@9{®Gáz$@A{®Gáz$@I{®Gáz$@Q Ó@Ğ¥‰†?YMÊƒ:¨?ŠUnknown
ƒDeviceMatMul"-gradient_tape/sequential_20/dense_61/MatMul_1(1Év¾Ÿo"@9Év¾Ÿo"@AÉv¾Ÿo"@IÉv¾Ÿo"@QIóÅ?I„?YGÍàÒL­?ŠUnknown
ƒDeviceMatMul"-gradient_tape/sequential_20/dense_62/MatMul_1(1®Gáz”@9®Gáz”@A®Gáz”@I®Gáz”@QıÍ1B´{?YoÀ‰´4W°?ŠUnknown
sDeviceMatMul"sequential_20/dense_62/MatMul(1®Gáz”@9®Gáz”@A®Gáz”@I®Gáz”@QıÍ1B´{?YOİ¬øÿ²?ŠUnknown
“DeviceBiasAddGrad"8gradient_tape/sequential_20/dense_62/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“{?Ya 5¹¸³?ŠUnknown
‹	DeviceDynamicStitch".gradient_tape/mean_squared_error/DynamicStitch(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q Ó@Ğ¥‰v?Y›-’S!µ?ŠUnknown

DeviceMatMul"+gradient_tape/sequential_20/dense_62/MatMul(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q Ó@Ğ¥‰v?YÕ: ïí‰¶?ŠUnknown
ŸDeviceSquaredDifference">sequential_20/batch_normalization_40/moments/SquaredDifference(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q Ó@Ğ¥‰v?YH$Lˆò·?ŠUnknown
…DeviceMean"1sequential_20/batch_normalization_40/moments/mean(1{®Gáz@9{®Gáz@A{®Gáz@I{®Gáz@Q Ó@Ğ¥‰v?YIU(©"[¹?ŠUnknown
gDevice
LogicalAnd"
LogicalAnd(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QñKUØr?Yx}.°{º?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_1(1ÙÎ÷Sc@9ÙÎ÷Sc@AÙÎ÷Sc@IÙÎ÷Sc@QñKUØr?Y§·Ñ³=œ»?ŠUnknown
qDeviceRealDiv"Nadam/Nadam/update/truediv(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Y	n1¹¼¼?ŠUnknown
sDeviceRealDiv"Nadam/Nadam/update/truediv_3(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Ykf¯4İ½?ŠUnknown
kDeviceMul"Nadam/Nadam/update_1/mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?YÍ=¨,°ı¾?ŠUnknown
mDeviceSqrt"Nadam/Nadam/update_4/Sqrt(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Y—Š"ÕÀ?ŠUnknown
^DevicePow"Nadam/Pow_2(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?YHöğ“SŸÀ?ŠUnknown
dDeviceDivNoNan"div_no_nan_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Yùa¿R‘/Á?ŠUnknown
‰DeviceTile"5gradient_tape/mean_squared_error/weighted_loss/Tile_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?YªÍÏ¿Á?ŠUnknown
™DeviceMul"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_1/Mul(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Y[9\ĞPÂ?ŠUnknown
‘DeviceSub">gradient_tape/sequential_20/batch_normalization_41/moments/sub(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Y¥*JàÂ?ŠUnknown
“DeviceBiasAddGrad"8gradient_tape/sequential_20/dense_61/BiasAdd/BiasAddGrad(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Y½ùMˆpÃ?ŠUnknown
‰DeviceAddV2"4sequential_20/batch_normalization_40/batchnorm/add_1(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Yn|ÇÆ Ä?ŠUnknown
…DeviceMean"1sequential_20/batch_normalization_41/moments/mean(1ü©ñÒMb@9ü©ñÒMb@Aü©ñÒMb@Iü©ñÒMb@QvÍÙ·r?Yè•Ë‘Ä?ŠUnknown
vDeviceAssignAddVariableOp"AssignAddVariableOp(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YÊ¥Œ;ıÄ?ŠUnknown
iDeviceSub"Nadam/Nadam/update/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YucƒqriÅ?ŠUnknown
mDeviceAddV2"Nadam/Nadam/update_1/add(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y !zÄ©ÕÅ?ŠUnknown
qDeviceSquare"Nadam/Nadam/update_2/Square(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YËŞpáAÆ?ŠUnknown
uDeviceRealDiv"Nadam/Nadam/update_2/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Yvœgj®Æ?ŠUnknown
m DeviceMul"Nadam/Nadam/update_3/mul_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y!Z^½OÇ?ŠUnknown
m!DeviceMul"Nadam/Nadam/update_3/mul_6(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YÌU‡†Ç?ŠUnknown
k"DeviceSub"Nadam/Nadam/update_3/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YwÕKc¾òÇ?ŠUnknown
u#DeviceRealDiv"Nadam/Nadam/update_4/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y"“B¶õ^È?ŠUnknown
m$DeviceMul"Nadam/Nadam/update_6/mul_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YÍP9	-ËÈ?ŠUnknown
k%DeviceSub"Nadam/Nadam/update_6/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Yx0\d7É?ŠUnknown
u&DeviceRealDiv"Nadam/Nadam/update_6/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y#Ì&¯›£É?ŠUnknown
u'DeviceRealDiv"Nadam/Nadam/update_8/truediv_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YÎ‰ÓÊ?ŠUnknown
m(DeviceMul"Nadam/Nadam/update_9/mul_4(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YyGU
|Ê?ŠUnknown
\)DeviceSub"	Nadam/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y$¨AèÊ?ŠUnknown
^*DeviceSub"Nadam/sub_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YÏÂûxTË?ŠUnknown
Ÿ+Device	RsqrtGrad"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/RsqrtGrad(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Yz€øM°ÀË?ŠUnknown
—,DeviceNeg"Dgradient_tape/sequential_20/batch_normalization_41/batchnorm/sub/Neg(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y%>ï ç,Ì?ŠUnknown
…-DeviceSquaredDifference"$mean_squared_error/SquaredDifference(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YĞûåó™Ì?ŠUnknown
‹.DeviceSub"8sequential_20/batch_normalization_40/AssignMovingAvg/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y{¹ÜFVÍ?ŠUnknown
‡/DeviceMul"4sequential_20/batch_normalization_40/batchnorm/mul_2(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y&wÓ™qÍ?ŠUnknown
…0DeviceSub"2sequential_20/batch_normalization_41/batchnorm/sub(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?YÑ4ÊìÄİÍ?ŠUnknown
u1DeviceBiasAdd"sequential_20/dense_60/BiasAdd(1/İ$•@9/İ$•@A/İ$•@I/İ$•@QÕj¯½Ôk?Y|òÀ?üIÎ?ŠUnknown
x2DeviceAssignAddVariableOp"AssignAddVariableOp_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YAÃÛ*¶Î?ŠUnknown
x3DeviceAssignAddVariableOp"AssignAddVariableOp_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y”öİX"Ï?ŠUnknown
x4DeviceAssignAddVariableOp"AssignAddVariableOp_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YËd-‡Ï?ŠUnknown
X5DeviceCast"Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y5,|µúÏ?ŠUnknown
`6DeviceCast"Nadam/Cast_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y*ƒ£åq3Ğ?ŠUnknown
`7DeviceCast"Nadam/Cast_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YŒë0‰iĞ?ŠUnknown
‚8DeviceAssignAddVariableOp"Nadam/Nadam/AssignAddVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YîS¾4 ŸĞ?ŠUnknown
k9DeviceSqrt"Nadam/Nadam/update/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YP¼K\·ÕĞ?ŠUnknown
o:DeviceSquare"Nadam/Nadam/update/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y²$ÙƒÎÑ?ŠUnknown
k;DeviceAddV2"Nadam/Nadam/update/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yf«åAÑ?ŠUnknown
m<DeviceAddV2"Nadam/Nadam/update/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YvõóÒüwÑ?ŠUnknown
k=DeviceMul"Nadam/Nadam/update/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YØ]ú®Ñ?ŠUnknown
s>DeviceRealDiv"Nadam/Nadam/update/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y:Æ"+äÑ?ŠUnknown
m?DeviceMul"Nadam/Nadam/update_1/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yœ.œIBÒ?ŠUnknown
m@DeviceMul"Nadam/Nadam/update_1/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yş–)qYPÒ?ŠUnknown
sADeviceRealDiv"Nadam/Nadam/update_1/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y`ÿ¶˜p†Ò?ŠUnknown
uBDeviceRealDiv"Nadam/Nadam/update_1/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÂgDÀ‡¼Ò?ŠUnknown
uCDeviceRealDiv"Nadam/Nadam/update_1/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y$ĞÑçòÒ?ŠUnknown
mDDeviceSqrt"Nadam/Nadam/update_2/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y†8_¶(Ó?ŠUnknown
oEDeviceAddV2"Nadam/Nadam/update_2/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yè ì6Í^Ó?ŠUnknown
oFDeviceAddV2"Nadam/Nadam/update_2/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YJ	z^ä”Ó?ŠUnknown
mGDeviceMul"Nadam/Nadam/update_2/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y¬q†ûÊÓ?ŠUnknown
sHDeviceRealDiv"Nadam/Nadam/update_2/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÚ”­Ô?ŠUnknown
uIDeviceRealDiv"Nadam/Nadam/update_2/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YpB"Õ)7Ô?ŠUnknown
mJDeviceSqrt"Nadam/Nadam/update_3/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÒª¯ü@mÔ?ŠUnknown
oKDeviceAddV2"Nadam/Nadam/update_3/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y4=$X£Ô?ŠUnknown
sLDeviceRealDiv"Nadam/Nadam/update_3/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y–{ÊKoÙÔ?ŠUnknown
uMDeviceRealDiv"Nadam/Nadam/update_3/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YøãWs†Õ?ŠUnknown
uNDeviceRealDiv"Nadam/Nadam/update_3/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YZLåšEÕ?ŠUnknown
qODeviceSquare"Nadam/Nadam/update_4/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y¼´rÂ´{Õ?ŠUnknown
mPDeviceAddV2"Nadam/Nadam/update_4/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y êË±Õ?ŠUnknown
oQDeviceAddV2"Nadam/Nadam/update_4/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y€…ãçÕ?ŠUnknown
oRDeviceAddV2"Nadam/Nadam/update_4/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yâí9úÖ?ŠUnknown
kSDeviceMul"Nadam/Nadam/update_4/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YDV¨`TÖ?ŠUnknown
mTDeviceMul"Nadam/Nadam/update_4/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y¦¾5ˆ(ŠÖ?ŠUnknown
mUDeviceMul"Nadam/Nadam/update_4/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y'Ã¯?ÀÖ?ŠUnknown
mVDeviceMul"Nadam/Nadam/update_4/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YjP×VöÖ?ŠUnknown
kWDeviceSub"Nadam/Nadam/update_4/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÌ÷İşm,×?ŠUnknown
sXDeviceRealDiv"Nadam/Nadam/update_4/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y.`k&…b×?ŠUnknown
uYDeviceRealDiv"Nadam/Nadam/update_4/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÈøMœ˜×?ŠUnknown
uZDeviceRealDiv"Nadam/Nadam/update_4/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yò0†u³Î×?ŠUnknown
m[DeviceSqrt"Nadam/Nadam/update_5/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YT™ÊØ?ŠUnknown
o\DeviceAddV2"Nadam/Nadam/update_5/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y¶¡Äá:Ø?ŠUnknown
k]DeviceMul"Nadam/Nadam/update_5/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yj.ìøpØ?ŠUnknown
m^DeviceMul"Nadam/Nadam/update_5/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YzÒ»§Ø?ŠUnknown
m_DeviceMul"Nadam/Nadam/update_5/mul_4(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÜ:I;'İØ?ŠUnknown
m`DeviceMul"Nadam/Nadam/update_5/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y>£Öb>Ù?ŠUnknown
saDeviceRealDiv"Nadam/Nadam/update_5/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y dŠUIÙ?ŠUnknown
ubDeviceRealDiv"Nadam/Nadam/update_5/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Ytñ±lÙ?ŠUnknown
ucDeviceRealDiv"Nadam/Nadam/update_5/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YdÜ~ÙƒµÙ?ŠUnknown
udDeviceRealDiv"Nadam/Nadam/update_5/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÆD›ëÙ?ŠUnknown
meDeviceSqrt"Nadam/Nadam/update_6/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y(­™(²!Ú?ŠUnknown
ofDeviceAddV2"Nadam/Nadam/update_6/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YŠ'PÉWÚ?ŠUnknown
ogDeviceAddV2"Nadam/Nadam/update_6/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yì}´wàÚ?ŠUnknown
khDeviceMul"Nadam/Nadam/update_6/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YNæAŸ÷ÃÚ?ŠUnknown
miDeviceMul"Nadam/Nadam/update_6/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y°NÏÆúÚ?ŠUnknown
sjDeviceRealDiv"Nadam/Nadam/update_6/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y·\î%0Û?ŠUnknown
ukDeviceRealDiv"Nadam/Nadam/update_6/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Ytê=fÛ?ŠUnknown
mlDeviceSqrt"Nadam/Nadam/update_7/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÖ‡w=TœÛ?ŠUnknown
qmDeviceSquare"Nadam/Nadam/update_7/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y8ğekÒÛ?ŠUnknown
onDeviceAddV2"Nadam/Nadam/update_7/add_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YšX’Œ‚Ü?ŠUnknown
koDeviceMul"Nadam/Nadam/update_7/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YüÀ´™>Ü?ŠUnknown
mpDeviceMul"Nadam/Nadam/update_7/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y^)­Û°tÜ?ŠUnknown
mqDeviceMul"Nadam/Nadam/update_7/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÀ‘:ÈªÜ?ŠUnknown
mrDeviceMul"Nadam/Nadam/update_7/mul_6(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y"úÇ*ßàÜ?ŠUnknown
ksDeviceSub"Nadam/Nadam/update_7/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y„bURöİ?ŠUnknown
utDeviceRealDiv"Nadam/Nadam/update_7/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YæÊâyMİ?ŠUnknown
uuDeviceRealDiv"Nadam/Nadam/update_7/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YH3p¡$ƒİ?ŠUnknown
ovDeviceAddV2"Nadam/Nadam/update_8/add_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yª›ıÈ;¹İ?ŠUnknown
mwDeviceMul"Nadam/Nadam/update_8/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y‹ğRïİ?ŠUnknown
sxDeviceRealDiv"Nadam/Nadam/update_8/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Ynlj%Ş?ŠUnknown
uyDeviceRealDiv"Nadam/Nadam/update_8/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YĞÔ¥?[Ş?ŠUnknown
mzDeviceSqrt"Nadam/Nadam/update_9/Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y2=3g˜‘Ş?ŠUnknown
q{DeviceSquare"Nadam/Nadam/update_9/Square(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y”¥À¯ÇŞ?ŠUnknown
m|DeviceAddV2"Nadam/Nadam/update_9/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YöN¶ÆıŞ?ŠUnknown
m}DeviceMul"Nadam/Nadam/update_9/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YXvÛİİ3ß?ŠUnknown
m~DeviceMul"Nadam/Nadam/update_9/mul_5(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YºŞhõiß?ŠUnknown
uDeviceRealDiv"Nadam/Nadam/update_9/truediv_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YGö, ß?ŠUnknown
v€DeviceRealDiv"Nadam/Nadam/update_9/truediv_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y~¯ƒT#Öß?ŠUnknown
]DevicePow"	Nadam/Pow(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yğ‹>à?ŠUnknown
_‚DeviceAddV2"	Nadam/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y!@ÏÑ(!à?ŠUnknown
aƒDeviceAddV2"Nadam/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YRô•e4<à?ŠUnknown
i„DeviceAddN"Nadam/gradients/AddN(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yƒ¨\ù?Wà?ŠUnknown
k…DeviceAddN"Nadam/gradients/AddN_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y´\#Krà?ŠUnknown
k†DeviceAddN"Nadam/gradients/AddN_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yåê Wà?ŠUnknown
k‡DeviceAddN"Nadam/gradients/AddN_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÅ°´b¨à?ŠUnknown
_ˆDeviceMul"Nadam/mul_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YGywHnÃà?ŠUnknown
_‰DeviceMul"Nadam/mul_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yx->ÜyŞà?ŠUnknown
_ŠDeviceSub"Nadam/sub_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y©áp…ùà?ŠUnknown
_‹DeviceSub"Nadam/sub_3(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÚ•Ë‘á?ŠUnknown
YŒDeviceSqrt"Sqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YJ’—œ/á?ŠUnknown
YDeviceSum"Sum_2(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y<şX+¨Já?ŠUnknown
zDeviceCast"%gradient_tape/mean_squared_error/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Ym²¿³eá?ŠUnknown
€DeviceRealDiv"(gradient_tape/mean_squared_error/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YfæR¿€á?ŠUnknown
˜DeviceDivNoNan"?gradient_tape/mean_squared_error/weighted_loss/value/div_no_nan(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÏ­æÊ›á?ŠUnknown
œ‘DeviceSum"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/add_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y ÏszÖ¶á?ŠUnknown
š’DeviceMul"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_1/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y1ƒ:âÑá?ŠUnknown
œ“DeviceSum"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yb7¢íìá?ŠUnknown
˜”DeviceNeg"Dgradient_tape/sequential_20/batch_normalization_40/batchnorm/sub/Neg(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y“ëÇ5ùâ?ŠUnknown
¢•DeviceBroadcastTo"Fgradient_tape/sequential_20/batch_normalization_40/moments/BroadcastTo(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÄŸÉ#â?ŠUnknown
¤–DeviceBroadcastTo"Hgradient_tape/sequential_20/batch_normalization_40/moments/BroadcastTo_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YõSU]>â?ŠUnknown
’—DeviceSub">gradient_tape/sequential_20/batch_normalization_40/moments/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y&ñYâ?ŠUnknown
š˜DeviceRealDiv"Bgradient_tape/sequential_20/batch_normalization_40/moments/truediv(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YW¼â„'tâ?ŠUnknown
œ™DeviceRealDiv"Dgradient_tape/sequential_20/batch_normalization_40/moments/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yˆp©3â?ŠUnknown
œšDeviceSum"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/add_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y¹$p¬>ªâ?ŠUnknown
˜›DeviceMul"Dgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul/Mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YêØ6@JÅâ?ŠUnknown
šœDeviceMul"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YıÓUàâ?ŠUnknown
œDeviceMul"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_1/Mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YLAÄgaûâ?ŠUnknown
œDeviceSum"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_1/Sum_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y}õŠûlã?ŠUnknown
¢ŸDeviceBroadcastTo"Fgradient_tape/sequential_20/batch_normalization_41/moments/BroadcastTo(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y®©Qx1ã?ŠUnknown
¤ DeviceBroadcastTo"Hgradient_tape/sequential_20/batch_normalization_41/moments/BroadcastTo_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yß]#„Lã?ŠUnknown
œ¡DeviceRealDiv"Dgradient_tape/sequential_20/batch_normalization_41/moments/truediv_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yß¶gã?ŠUnknown
”¢DeviceBiasAddGrad"8gradient_tape/sequential_20/dense_60/BiasAdd/BiasAddGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YAÆ¥J›‚ã?ŠUnknown
„£DeviceEluGrad",gradient_tape/sequential_20/dense_60/EluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YrzlŞ¦ã?ŠUnknown
„¤DeviceEluGrad",gradient_tape/sequential_20/dense_61/EluGrad(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y£.3r²¸ã?ŠUnknown
‡¥DeviceCast"2mean_squared_error/weighted_loss/num_elements/Cast(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÔâù¾Óã?ŠUnknown
¦DeviceDivNoNan"&mean_squared_error/weighted_loss/value(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y—À™Éîã?ŠUnknown
¬§DeviceAssignSubVariableOp"Hsequential_20/batch_normalization_40/AssignMovingAvg/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y6K‡-Õ	ä?ŠUnknown
¨DeviceSub":sequential_20/batch_normalization_40/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YgÿMÁà$ä?ŠUnknown
Š©DeviceRsqrt"4sequential_20/batch_normalization_40/batchnorm/Rsqrt(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y˜³Uì?ä?ŠUnknown
ˆªDeviceMul"4sequential_20/batch_normalization_40/batchnorm/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÉgÛè÷Zä?ŠUnknown
Š«DeviceMean"5sequential_20/batch_normalization_40/moments/variance(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yú¢|vä?ŠUnknown
Œ¬DeviceMul"8sequential_20/batch_normalization_41/AssignMovingAvg/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y+Ğh‘ä?ŠUnknown
Œ­DeviceSub"8sequential_20/batch_normalization_41/AssignMovingAvg/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y\„/¤¬ä?ŠUnknown
®®DeviceAssignSubVariableOp"Jsequential_20/batch_normalization_41/AssignMovingAvg_1/AssignSubVariableOp(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y8ö7&Çä?ŠUnknown
¯DeviceSub":sequential_20/batch_normalization_41/AssignMovingAvg_1/sub(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y¾ì¼Ë1âä?ŠUnknown
ˆ°DeviceAddV2"2sequential_20/batch_normalization_41/batchnorm/add(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yï ƒ_=ıä?ŠUnknown
Š±DeviceAddV2"4sequential_20/batch_normalization_41/batchnorm/add_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y UJóHå?ŠUnknown
†²DeviceMul"2sequential_20/batch_normalization_41/batchnorm/mul(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YQ	‡T3å?ŠUnknown
ˆ³DeviceMul"4sequential_20/batch_normalization_41/batchnorm/mul_1(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y‚½×`Nå?ŠUnknown
 ´DeviceSquaredDifference">sequential_20/batch_normalization_41/moments/SquaredDifference(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Y³q®kiå?ŠUnknown
ŠµDeviceMean"5sequential_20/batch_normalization_41/moments/variance(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?Yä%eBw„å?ŠUnknown
n¶DeviceElu"sequential_20/dense_60/Elu(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YÚ+Ö‚Ÿå?ŠUnknown
n·DeviceElu"sequential_20/dense_61/Elu(1ú~j¼t“@9ú~j¼t“@Aú~j¼t“@Iú~j¼t“@Q'1´Æ“k?YFòiºå?ŠUnknown
W¸DeviceMul"Mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?YöVÃb˜Ìå?ŠUnknown
n¹DeviceSqrt"Nadam/Nadam/update_1/Sqrt(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y¦”[¢Şå?ŠUnknown
pºDeviceAddV2"Nadam/Nadam/update_1/add_3(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?YVèdT¬ğå?ŠUnknown
l»DeviceMul"Nadam/Nadam/update_2/mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y±5M¶æ?ŠUnknown
n¼DeviceMul"Nadam/Nadam/update_3/mul_4(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y¶yFÀæ?ŠUnknown
n½DeviceAddV2"Nadam/Nadam/update_7/add(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?YfB×>Ê&æ?ŠUnknown
n¾DeviceSqrt"Nadam/Nadam/update_8/Sqrt(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y¨7Ô8æ?ŠUnknown
n¿DeviceMul"Nadam/Nadam/update_8/mul_4(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?YÆÓx0ŞJæ?ŠUnknown
pÀDeviceAddV2"Nadam/Nadam/update_9/add_2(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?YvœI)è\æ?ŠUnknown
lÁDeviceMul"Nadam/Nadam/update_9/mul(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y&e"ònæ?ŠUnknown
nÂDeviceMul"Nadam/Nadam/update_9/mul_2(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?YÖ-ëü€æ?ŠUnknown
lÃDeviceSub"Nadam/Nadam/update_9/sub(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y†ö»“æ?ŠUnknown
_ÄDeviceMul"Nadam/mul_6(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y6¿Œ¥æ?ŠUnknown
xÅDeviceSub"$gradient_tape/mean_squared_error/sub(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Yæ‡]·æ?ŠUnknown
ŠÆDeviceRsqrt"4sequential_20/batch_normalization_41/batchnorm/Rsqrt(11¬Zd @91¬Zd @A1¬Zd @I1¬Zd @QÈ¯ÈĞø	b?Y–P.ş#Éæ?ŠUnknown
yÇDeviceAssignAddVariableOp"AssignAddVariableOp_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¶+Ûæ?ŠUnknown
[ÈDeviceCast"Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y‚ëám3íæ?ŠUnknown
hÉDevice_Send"IteratorGetNext/_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yø¸»%;ÿæ?ŠUnknown
nÊDeviceAddV2"Nadam/Nadam/update/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yn†•İBç?ŠUnknown
nËDeviceAddV2"Nadam/Nadam/update/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YäSo•J#ç?ŠUnknown
jÌDeviceMul"Nadam/Nadam/update/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YZ!IMR5ç?ŠUnknown
lÍDeviceMul"Nadam/Nadam/update/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YĞî"ZGç?ŠUnknown
lÎDeviceMul"Nadam/Nadam/update/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YF¼ü¼aYç?ŠUnknown
lÏDeviceMul"Nadam/Nadam/update/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¼‰Ötikç?ŠUnknown
lĞDeviceMul"Nadam/Nadam/update/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y2W°,q}ç?ŠUnknown
lÑDeviceMul"Nadam/Nadam/update/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¨$Šäxç?ŠUnknown
rÒDeviceSquare"Nadam/Nadam/update_1/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yòcœ€¡ç?ŠUnknown
pÓDeviceAddV2"Nadam/Nadam/update_1/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y”¿=Tˆ³ç?ŠUnknown
pÔDeviceAddV2"Nadam/Nadam/update_1/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y
Åç?ŠUnknown
nÕDeviceMul"Nadam/Nadam/update_1/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y€ZñÃ—×ç?ŠUnknown
nÖDeviceMul"Nadam/Nadam/update_1/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yö'Ë{Ÿéç?ŠUnknown
n×DeviceMul"Nadam/Nadam/update_1/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Ylõ¤3§ûç?ŠUnknown
nØDeviceMul"Nadam/Nadam/update_1/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YâÂ~ë®è?ŠUnknown
lÙDeviceSub"Nadam/Nadam/update_1/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YXX£¶è?ŠUnknown
vÚDeviceRealDiv"Nadam/Nadam/update_1/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÎ]2[¾1è?ŠUnknown
nÛDeviceAddV2"Nadam/Nadam/update_2/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YD+ÆCè?ŠUnknown
pÜDeviceAddV2"Nadam/Nadam/update_2/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YºøåÊÍUè?ŠUnknown
nİDeviceMul"Nadam/Nadam/update_2/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y0Æ¿‚Õgè?ŠUnknown
nŞDeviceMul"Nadam/Nadam/update_2/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¦“™:İyè?ŠUnknown
nßDeviceMul"Nadam/Nadam/update_2/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yasòä‹è?ŠUnknown
nàDeviceMul"Nadam/Nadam/update_2/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y’.Mªìè?ŠUnknown
náDeviceMul"Nadam/Nadam/update_2/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yü&bô¯è?ŠUnknown
lâDeviceSub"Nadam/Nadam/update_2/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y~É üÁè?ŠUnknown
vãDeviceRealDiv"Nadam/Nadam/update_2/truediv_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yô–ÚÑÔè?ŠUnknown
räDeviceSquare"Nadam/Nadam/update_3/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yjd´‰æè?ŠUnknown
nåDeviceAddV2"Nadam/Nadam/update_3/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yà1Aøè?ŠUnknown
pæDeviceAddV2"Nadam/Nadam/update_3/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YVÿgù
é?ŠUnknown
pçDeviceAddV2"Nadam/Nadam/update_3/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÌÌA±"é?ŠUnknown
lèDeviceMul"Nadam/Nadam/update_3/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YBši*.é?ŠUnknown
néDeviceMul"Nadam/Nadam/update_3/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¸gõ 2@é?ŠUnknown
nêDeviceMul"Nadam/Nadam/update_3/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y.5ÏØ9Ré?ŠUnknown
nëDeviceMul"Nadam/Nadam/update_3/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¤©Adé?ŠUnknown
vìDeviceRealDiv"Nadam/Nadam/update_3/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YĞ‚HIvé?ŠUnknown
píDeviceAddV2"Nadam/Nadam/update_4/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y\ Qˆé?ŠUnknown
nîDeviceMul"Nadam/Nadam/update_4/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yk6¸Xšé?ŠUnknown
nïDeviceMul"Nadam/Nadam/update_4/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y|8p`¬é?ŠUnknown
nğDeviceMul"Nadam/Nadam/update_4/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yòê'h¾é?ŠUnknown
rñDeviceSquare"Nadam/Nadam/update_5/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YhÓÃßoĞé?ŠUnknown
nòDeviceAddV2"Nadam/Nadam/update_5/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YŞ —wâé?ŠUnknown
póDeviceAddV2"Nadam/Nadam/update_5/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YTnwOôé?ŠUnknown
pôDeviceAddV2"Nadam/Nadam/update_5/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÊ;Q‡ê?ŠUnknown
nõDeviceMul"Nadam/Nadam/update_5/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y@	+¿ê?ŠUnknown
nöDeviceMul"Nadam/Nadam/update_5/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¶Öw–*ê?ŠUnknown
n÷DeviceMul"Nadam/Nadam/update_5/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y,¤Ş.<ê?ŠUnknown
løDeviceSub"Nadam/Nadam/update_5/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¢q¸æ¥Nê?ŠUnknown
rùDeviceSquare"Nadam/Nadam/update_6/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y?’­`ê?ŠUnknown
núDeviceAddV2"Nadam/Nadam/update_6/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YlVµrê?ŠUnknown
pûDeviceAddV2"Nadam/Nadam/update_6/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÚE½„ê?ŠUnknown
nüDeviceMul"Nadam/Nadam/update_6/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yz§ÆÄ–ê?ŠUnknown
nıDeviceMul"Nadam/Nadam/update_6/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yğtù}Ì¨ê?ŠUnknown
nşDeviceMul"Nadam/Nadam/update_6/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YfBÓ5Ôºê?ŠUnknown
nÿDeviceMul"Nadam/Nadam/update_6/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÜ­íÛÌê?ŠUnknown
v€DeviceRealDiv"Nadam/Nadam/update_6/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YRİ†¥ãŞê?ŠUnknown
pDeviceAddV2"Nadam/Nadam/update_7/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÈª`]ëğê?ŠUnknown
p‚DeviceAddV2"Nadam/Nadam/update_7/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y>x:óë?ŠUnknown
nƒDeviceMul"Nadam/Nadam/update_7/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y´EÍúë?ŠUnknown
n„DeviceMul"Nadam/Nadam/update_7/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y*î„'ë?ŠUnknown
n…DeviceMul"Nadam/Nadam/update_7/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y àÇ<
9ë?ŠUnknown
t†DeviceRealDiv"Nadam/Nadam/update_7/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y®¡ôKë?ŠUnknown
v‡DeviceRealDiv"Nadam/Nadam/update_7/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YŒ{{¬]ë?ŠUnknown
rˆDeviceSquare"Nadam/Nadam/update_8/Square(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YIUd!oë?ŠUnknown
n‰DeviceAddV2"Nadam/Nadam/update_8/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yx/)ë?ŠUnknown
pŠDeviceAddV2"Nadam/Nadam/update_8/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YîãÔ0“ë?ŠUnknown
p‹DeviceAddV2"Nadam/Nadam/update_8/add_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yd±â‹8¥ë?ŠUnknown
lŒDeviceMul"Nadam/Nadam/update_8/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÚ~¼C@·ë?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YPL–ûGÉë?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÆp³OÛë?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y<çIkWíë?ŠUnknown
nDeviceMul"Nadam/Nadam/update_8/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y²´##_ÿë?ŠUnknown
l‘DeviceSub"Nadam/Nadam/update_8/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y(‚ıÚfì?ŠUnknown
v’DeviceRealDiv"Nadam/Nadam/update_8/truediv_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YO×’n#ì?ŠUnknown
p“DeviceAddV2"Nadam/Nadam/update_9/add_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y±Jv5ì?ŠUnknown
p”DeviceAddV2"Nadam/Nadam/update_9/add_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YŠêŠ~Gì?ŠUnknown
n•DeviceMul"Nadam/Nadam/update_9/mul_3(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y ¸dº…Yì?ŠUnknown
n–DeviceMul"Nadam/Nadam/update_9/mul_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yv…>rkì?ŠUnknown
t—DeviceRealDiv"Nadam/Nadam/update_9/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YìR*•}ì?ŠUnknown
v˜DeviceRealDiv"Nadam/Nadam/update_9/truediv_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yb òáœì?ŠUnknown
_™DevicePow"Nadam/Pow_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YØíË™¤¡ì?ŠUnknown
]šDeviceMul"	Nadam/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YN»¥Q¬³ì?ŠUnknown
_›DeviceMul"Nadam/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÄˆ	´Åì?ŠUnknown
_œDeviceMul"Nadam/mul_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y:VYÁ»×ì?ŠUnknown
_DeviceMul"Nadam/mul_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y°#3yÃéì?ŠUnknown
_DeviceMul"Nadam/mul_7(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y&ñ1Ëûì?ŠUnknown
_ŸDeviceSub"Nadam/sub_4(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yœ¾æèÒí?ŠUnknown
_ DeviceSub"Nadam/sub_5(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YŒÀ Úí?ŠUnknown
_¡DeviceSub"Nadam/sub_6(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YˆYšXâ1í?ŠUnknown
_¢DeviceSub"Nadam/sub_7(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yş&têCí?ŠUnknown
c£DeviceDivNoNan"
div_no_nan(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YtôMÈñUí?ŠUnknown
¤Device_Recv")gradient_tape/mean_squared_error/Fill/_20(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YêÁ'€ùgí?ŠUnknown
x¥DeviceMul"$gradient_tape/mean_squared_error/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y`8zí?ŠUnknown
z¦DeviceMul"&gradient_tape/mean_squared_error/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÖ\ÛïŒí?ŠUnknown
˜§DeviceMul"Dgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YL*µ§í?ŠUnknown
š¨DeviceMul"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÂ÷_°í?ŠUnknown
œ©DeviceMul"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_1/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y8Åh Âí?ŠUnknown
šªDeviceMul"Fgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y®’BÏ'Ôí?ŠUnknown
œ«DeviceMul"Hgradient_tape/sequential_20/batch_normalization_40/batchnorm/mul_2/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y$`‡/æí?ŠUnknown
”¬DeviceCast"?gradient_tape/sequential_20/batch_normalization_40/moments/Cast(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yš-ö>7øí?ŠUnknown
–­DeviceCast"Agradient_tape/sequential_20/batch_normalization_40/moments/Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YûÏö>
î?ŠUnknown
’®DeviceMul">gradient_tape/sequential_20/batch_normalization_40/moments/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y†È©®Fî?ŠUnknown
¯Device_Recv"Hgradient_tape/sequential_20/batch_normalization_40/moments/floordiv_1/_8(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yü•ƒfN.î?ŠUnknown
”°DeviceMul"@gradient_tape/sequential_20/batch_normalization_40/moments/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yrc]V@î?ŠUnknown
 ±Device	RsqrtGrad"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/RsqrtGrad(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yè07Ö]Rî?ŠUnknown
š²DeviceMul"Fgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_2/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y^şedî?ŠUnknown
œ³DeviceMul"Hgradient_tape/sequential_20/batch_normalization_41/batchnorm/mul_2/Mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÔËêEmvî?ŠUnknown
”´DeviceCast"?gradient_tape/sequential_20/batch_normalization_41/moments/Cast(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YJ™Äıtˆî?ŠUnknown
–µDeviceCast"Agradient_tape/sequential_20/batch_normalization_41/moments/Cast_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÀfµ|šî?ŠUnknown
’¶DeviceMul">gradient_tape/sequential_20/batch_normalization_41/moments/Mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y64xm„¬î?ŠUnknown
”·DeviceMul"@gradient_tape/sequential_20/batch_normalization_41/moments/mul_1(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¬R%Œ¾î?ŠUnknown
š¸DeviceRealDiv"Bgradient_tape/sequential_20/batch_normalization_41/moments/truediv(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y"Ï+İ“Ğî?ŠUnknown
x¹DeviceSum"$mean_squared_error/weighted_loss/Sum(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y˜œ•›âî?ŠUnknown
ŒºDeviceMul"8sequential_20/batch_normalization_40/AssignMovingAvg/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YjßL£ôî?ŠUnknown
®»DeviceAssignSubVariableOp"Jsequential_20/batch_normalization_40/AssignMovingAvg_1/AssignSubVariableOp(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y„7¹«ï?ŠUnknown
¼DeviceMul":sequential_20/batch_normalization_40/AssignMovingAvg_1/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yú“¼²ï?ŠUnknown
ˆ½DeviceAddV2"2sequential_20/batch_normalization_40/batchnorm/add(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YpÒltº*ï?ŠUnknown
†¾DeviceMul"2sequential_20/batch_normalization_40/batchnorm/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YæŸF,Â<ï?ŠUnknown
†¿DeviceSub"2sequential_20/batch_normalization_40/batchnorm/sub(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y\m äÉNï?ŠUnknown
¬ÀDeviceAssignSubVariableOp"Hsequential_20/batch_normalization_41/AssignMovingAvg/AssignSubVariableOp(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YÒ:ú›Ñ`ï?ŠUnknown
ÁDeviceMul":sequential_20/batch_normalization_41/AssignMovingAvg_1/mul(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?YHÔSÙrï?ŠUnknown
ˆÂDeviceMul"4sequential_20/batch_normalization_41/batchnorm/mul_2(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y¾Õ­á„ï?ŠUnknown
vÃDeviceBiasAdd"sequential_20/dense_61/BiasAdd(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Y4£‡Ãè–ï?ŠUnknown
vÄDeviceBiasAdd"sequential_20/dense_62/BiasAdd(1ü©ñÒMb @9ü©ñÒMb @Aü©ñÒMb @Iü©ñÒMb @QvÍÙ·b?Yªpa{ğ¨ï?ŠUnknown
ŒÅDevice	_HostRecv"2gradient_tape/mean_squared_error/DynamicStitch/_26(1‰A`åĞ"û?9‰A`åĞ"û?A‰A`åĞ"û?I‰A`åĞ"û?QšK¼€ÈÜ]?YĞÎ¡ßŞ·ï?ŠUnknown
ÆDevice_Recv"+gradient_tape/mean_squared_error/Prod_1/_22(1ffffffğ?9ffffffğ?Affffffğ?Iffffffğ?QwéÃÇ9R?YÅ°…üäÀï?ŠUnknown
hÇDevice_Send"IteratorGetNext/_3(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?Y€—rØèÉï?ŠUnknown
^ÈDevice_Recv"Size/_16(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?Y;~_´ìÒï?ŠUnknown
€ÉDevice_Recv"*gradient_tape/mean_squared_error/Shape/_18(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?YödLğÛï?ŠUnknown
ƒÊDevice_Recv"-gradient_tape/mean_squared_error/floordiv/_24(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?Y±K9lôäï?ŠUnknown
ËDevice_Recv"Ggradient_tape/sequential_20/batch_normalization_40/moments/floordiv/_10(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?Yl2&Høíï?ŠUnknown
ŸÌDevice_Recv"Igradient_tape/sequential_20/batch_normalization_41/moments/floordiv_1/_12(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?Y'$üöï?ŠUnknown
fÍDevice_Recv"strided_slice/_6(1ü©ñÒMbğ?9ü©ñÒMbğ?Aü©ñÒMbğ?Iü©ñÒMbğ?QvÍÙ·R?Yâÿÿÿÿÿï?ŠUnknown
pÎDevice_Recv"Ggradient_tape/sequential_20/batch_normalization_41/moments/floordiv/_14(Yâÿÿÿÿÿï?ŠUnknown
vÏHostFlushSummaryWriter"FlushSummaryWriter(1{®Gáã“@9{®Gáã“@A{®Gáã“@I{®Gáã“@aN¢ñkç\æ?iN¢ñkç\æ?ŠUnknown
fĞHost_Send"IteratorGetNext/_3(1²ï§Æÿe@9²ï§Æÿe@A²ï§Æÿe@I²ï§Æÿe@aÅA†ë»¸?iïÚ¹Üdté?ŠUnknown
fÑHost_Send"IteratorGetNext/_1(1Zd;ßOÅa@9Zd;ßOÅa@AZd;ßOÅa@IZd;ßOÅa@a-Ìp?âú³?iuô§$Áóë?ŠUnknown
fÒHost
LogicalAnd"
LogicalAnd(1^ºI«P@9^ºI«P@A^ºI«P@I^ºI«P@aÕj…Ñ{½¢?i"KÀá˜í?ŠUnknown
jÓHostWriteSummary"WriteSummary(1V-²oL@9V-²oL@AV-²oL@IV-²oL@a^ÎµøŸ?i¼n×]î?ŠUnknown
‹ÔHostDataset"5Iterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat(1Év¾Ÿo8@9Év¾Ÿo8@AÙÎ÷Sƒ4@IÙÎ÷Sƒ4@aÿÇb³,‡?i%G<Š{î?ŠUnknown
eÕHostDataset"Iterator::Model(1¸…ëQ˜?@9¸…ëQ˜?@Aü©ñÒMB0@Iü©ñÒMB0@aşÆIÃG‚?iA¶`—½Äî?ŠUnknown
tÖHostDataset"Iterator::Model::ParallelMapV2(1yé&1¬.@9yé&1¬.@Ayé&1¬.@Iyé&1¬.@a22u>?i
Ó4ıµ	ï?ŠUnknown
_×HostGatherV2"GatherV2(1ö(\Âu(@9ö(\Âu(@Aö(\Âu(@Iö(\Âu(@awÖœK9€{?i·Ìo¶@ï?ŠUnknown
•ØHostDataset"?Iterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate(1î|?5^º2@9î|?5^º2@Ah‘í|?µ$@Ih‘í|?µ$@a4WnùLHw?ieé¾	Goï?ŠUnknown
¥ÙHostDataset"OIterator::Model::ParallelMapV2::Zip[0]::FlatMap[0]::Concatenate[0]::TensorSlice(1sh‘í|¿ @9sh‘í|¿ @Ash‘í|¿ @Ish‘í|¿ @aìúª~‚Ôr?i[?¼ğ”ï?ŠUnknown
aÚHostGatherV2"
GatherV2_1(1øSã¥›D@9øSã¥›D@AøSã¥›D@IøSã¥›D@a$lË†Éhl?iÇ
CØX±ï?ŠUnknown
mÛHostIteratorGetNext"IteratorGetNext(1Tã¥›Ä @9Tã¥›Ä @ATã¥›Ä @ITã¥›Ä @a¾Ézáh?iÜÓ½Û9Êï?ŠUnknown
yÜHostDataset"#Iterator::Model::ParallelMapV2::Zip(1ºI+I@9ºI+I@AF¶óıÔø@IF¶óıÔø@aååhI”g?iÂ×%%Îáï?ŠUnknown
—İHostDataset"AIterator::Model::ParallelMapV2::Zip[1]::ForeverRepeat::FromTensor(1‘í|?5^@9‘í|?5^ÿ?A‘í|?5^@I‘í|?5^ÿ?a_ËLC¢a?iurhpóï?ŠUnknown
…ŞHostDataset"/Iterator::Model::ParallelMapV2::Zip[0]::FlatMap(1/İ$a4@9/İ$a4@AÑ"Ûù~jú?IÑ"Ûù~jú?a/¦Ù!6³M?i÷ëú5İúï?ŠUnknown
bßHostIdentity"Identity(1ƒÀÊ¡Eò?9ƒÀÊ¡Eò?AƒÀÊ¡Eò?IƒÀÊ¡Eò?aø&P(‹D?i      ğ?ŠUnknown2GPU